mercadopago/px-ios

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples.xcodeproj/project.pbxproj
- Cambio de nombre a la variable publicKey en MercadoPagoContext
=> - Hago compilar el proyecto cambiando el deployment target a 8.3

MercadoPagoSDK/MercadoPagoSDK/AmountInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Currency.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Se modifican los tipos de los atributos decimalSeparator y thousansSeparator en Currency de Character a String
=> Currency.decimalSeparator and Currency.thousandsSeparator types modified

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Token.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
-Se fixea el bug de Date parseado a String en Token
-Se agrega una función en Utils para transformar un Date a String de modo que pueda ser leído por JSON correctamente
=> Token to JSONString Bug fix (Cambio solicitado por HIB)

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostViewController.swift, MercadoPagoSDK/MercadoPagoSDK/WebViewController.xib, MercadoPagoSDKExamples/MercadoPagoSDKExamples/ServicesExamplesViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultViewController.m
Revision de Callback y CallbackCancel de todo el QSK
=> Callback cancel review

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Quick Fix CallbackCancel en PaymentVault
=> Quick Fix CallbackCancel en PaymentVault

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PreferenceDescriptionTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/UIColor+Additions.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/LaunchScreen.xib
=> Fix set color

MercadoPagoSDK/MercadoPagoSDK/InstallmentsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IssuersViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Payment.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodsViewController.swift
Fix solicitados por Híbrido (ETorres)
=> Fix for hib

MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
- Traducciones a portugués para formulario inline de tarjeta de crédito
=> CC form pt translations

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.xib, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.plist, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/TextMaskFormater.swift, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDKExamples/MercadoPagoSDKExamples.xcodeproj/xcshareddata/xcschemes/MercadoPagoSDKExamplesUITests.xcscheme, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/MainExamplesViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamplesUITests/CardFlowTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
1.  Se agrega un objeto para manejar enmascarados de TextFields y Labels. 
2. Se agregan funcionalidad de enmascarar y desenmascarar textos genericos.
3. Se quita la lógica de enmascarar el numero de tarjeta y se reemplaza por por el elemento agregado. (Se eliminan el 20% de las lineas de la clase CardFormViewController)
4. Se quita la misma lógica para DNI y se reemplaza por el mismo elemento. 
5. Se agregan las mascaras en el archivo (plist) de Payment Methods de modo que puedan decirnos con que mascara mostarlos en cada caso.
6. Se agregan las mascaras para CPF y CNPJ en la pantalla de documentos (Brasil).
7. Se agrega funcionalidad para que un Payment Method conozca su color y su imagen.
=> Input mask

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.swift
Agrego las urls para terms & conditions dependiendo del Site.
=> Agrego las urls para terms & conditions dependiendo del Site.

MercadoPagoSDK-BETA.podspec, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/TextMaskFormater.swift, MercadoPagoSDK/MercadoPagoSDKTests/MaskElementTest.swift
-Agrego test a TextMaskFormater
- Fix bugs
- Se cambian los caracteres de espacio y de lugar vacío de forma que ahora son Character (antes eran String)
=> Input mask test

MercadoPagoSDK/MercadoPagoSDKTests/BaseTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/GuessingFormTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoUIViewControllerTest.swift
=> Fix tests target

MercadoPagoSDK/MercadoPagoSDK/ApprovedPaymentHeaderTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/AuthorizePaymentBodyTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/AuthorizePaymentHeaderTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PendingPaymentHeaderTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PreferenceService.swift, MercadoPagoSDK/MercadoPagoSDK/RejectedPaymentBodyTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/RejectedPaymentHeaderTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDKTests/MPStepBuilderTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentCongratsViewControllerTest.swift
Habilita ambiente de BETA para todos los servicios de la SDK.
Este PR depende de #114
=> Beta testing

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/Pods/Pods.xcodeproj/project.pbxproj, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
- Mostrar 4 últimos dígitos para customer card en CHO / F3
- Mostrar 4 últimos dígitos para customer card en pantalla de cuotas (F2 / F3)
=> Override last four digits for customer cards

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/PayerCostViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift
- Opción de cambiar cuotas en RyC para customer card en F3
=> Change installments option for customer card

MercadoPagoSDK/MercadoPagoSDK/CardToken.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift
- Mensaje de error para tarjeta Master se veia incorrecto
- CardFormViewController nulo testeando en iphone
=> Hot fix devices cc

MercadoPagoSDK/MercadoPagoSDK/Payment.swift
Cambio de tipo para atributo de id
=> Proper id field type in JSONString

MercadoPagoSDK/MercadoPagoSDK/Issuer.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowController.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/Token.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
- _id matching fixes in toJSONs
- Force casting fix
=> Hot fixes reported by wallet

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDKExamples/MercadoPagoSDKExamples.xcodeproj/project.pbxproj
Fix #168 
- "Use legacy Swift version" seteado en NO
[x] Testeado en BETA con emulador
[x] Testeado en BETA con dispositivo
=> SWIFT_VERSION as 3.0.1

f1.html, f2.html, index.html
- URL's actualizadas
- Snippets de F2 actualizados con callbackCancel
[-] Testeado en BETA con emulador
[-] Testeado en BETA con dispositivo
[-] Test unitarios OK
[-] Test funcionales OK
[ X ] Documentación actualizada
=> Update html references. Update f2 methods.

f1.html, f2.html, index.html
- Versión de Pod actualizada
[X] Documentación actualizada
=> Update pod version to 2.0.8

MercadoPagoSDK/MercadoPagoSDK/Payer.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift
Fix #152
Payer en body de request con access_token
=> Request body fro groups as GroupsPayer. Solves issue #152

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #190
- Add loading
- Groups & Customer Cards
=> Se cargan  los grupos y las CCs todo junto

MercadoPagoSDK/MercadoPagoSDK/Utils.swift
Fix #194
- Cambio 1
Acepta solo fechas de 4 digitos
- Cambio 2
=> ExpirationDate Bug. Solves #194

MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #198
- Cambio 1
Agregué el callback cancel en MPFlowBuilder y le agregue el dismiss al mismo
- Cambio 2
=> Fix Add Callback Cancel MPFlow startPaymentVaultViewController Solves #198

MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/CardInformation.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
- Tarjetas guardadas skipea paso de bancos
- RyC muestra los dígitos de tarjeta guardada correctamente
=> Fixes for customer cards

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Ver issuers en CardAdditionalStep
=> Fix issuer

MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearch.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift
##  Cambios introducidos : 
- Obtener issuer para tarjetas guardadas
=> Get issuer from cards in groups

MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
=> Groups fixed with preference

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #222
- Calcula la altura de la sección para customer cards
=> Section height for customer cards with exclusions. Fix #222

MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.xib, README.md
Fix de labels mostrandose mal en medios de pago en grupos.
- Fix de height de labels en grupos
- Aproveché para actualizar el README.md :octocat: 
[X] Documentación actualizada
=> Fix labels in groups

README.md
Actualización de README.md
- Se actualiza link de documentación
- Se agrega versión de swift
- Se agrega requerimientos de versiones de cocoaPods y Xcode
=> Update README.md for cocoaPods documentation

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix issue de exclusiones con customer cards
- Se inicializan las customerCards en viewModel en F2 correctamente
=> Customer cards not considered with exclusions

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Closes #253 #254 
- Limpio la key de idempotencia al momento de iniciar el CHO
- Actualizo el numero de version
=> - Update Version number

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.xib, MercadoPagoSDK/MercadoPagoSDK/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
# Cambios introducidos : 
- Traducción de textos para México
=> Traducción textos Mexico

MercadoPagoSDK/MercadoPagoSDK/CardBackView.xib, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift
Fix #226 
- Agrande la tarjeta como pidio UX
- Arregle los constrains de la banda negra
=> Fix contains, bigger card in SecuriteCode

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Close #166 
- Se agrega tracker listener
- Se agrega el listener en el proyecto de ejemplo
- Se cambia la version a 3.0.0
- Se agregan nombres de algunas screens que faltaban
=> Tracking delegate

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Close #240 
- Se permite el seteo de cantidad custom de medios de pago del usuario en Contexto
Revisión 
Testeo
=> Custom customer pms

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift
Fix #250 
- Baja el teclado luego de continuar en el Security Code
Revisión
[] Todos los textos se encuentran localizables
[] No se introducen warnings al proyecto
Testeo
=> no message

.travis.yml
=> Testing travis

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultTitleCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultTitleCollectionViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #274 
- Se setea color de background general para todas las vistas
- Se oculta texto de section de titulo en PaymentVault
- Se corrige el texto por default 
Revisión
Testeo
=> Fixing scroll

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
- Corrección de titulo de navBar en RyC
Revisión
Testeo
=> Fix nav bar title ry c

MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Close #221 , #284
- Agrego "extra params" al delegate de tracker
- Updetee la version del api a 3.1.4
Revisión
Testeo
- Added extra params to tracker delegate
=> Update Tracker (extra params) & api_version

MercadoPagoSDK/MercadoPagoSDK/FooterTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings
Fix #291 
- Cambiar el "seguir comprando" por "continuar"
Revisión
[] No se introducen warnings al proyecto
Testeo
=> Changed "seguir comprando" to "continuar"

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift
Closes #286 
- Remueve el cache de grupos
Revisión
Testeo
=> Remove cache from groups

MercadoPagoSDK/MPLoadingView.m, MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Images.xcassets/mpui-loading_default.imageset/Contents.json, MercadoPagoSDK/MercadoPagoSDK/LoadingOverlay.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/WebViewController.swift, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/ExampleUtils.h
Fix #251 #272 #271 #245 
- Se agrega Loading custom según requerimiento de Wallet
- Default iOS sppiner en Loading
- Se agrega la opción de elegir en contexto entre Loading default o Loading Custom
- Se agrega Loading en CardAdditionalStep
- Se actualiza imagen de spinner en Loading Custom
Revisión
Testeo
=> Custom and Default Loading

MercadoPagoSDK/MercadoPagoSDK/InstructionBodyTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/es-CO.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-MX.lproj/Localizable.strings, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Fix #295 
- Agregue traducciones faltantes
- Resolución del método findPaymentMethod que traia a banamex como amex
Revisión
Testeo
- [] Test unitarios OK
- [] Test funcionales OK
- [] Documentación actualizada
=> Fixes para Mexico

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #304 
- Payment Preference en Customer Cards
Revisión
Testeo
=> Fix paymentPreference in Customer Cards

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIScrollViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostTitleTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultTitleCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultTitleCollectionViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #300 
- Se agregan dos colores en grupos
- Se achica el titulo de la pantalla cuando se scrollea
Revisión
Testeo
- [] Test unitarios OK
- [] Test funcionales OK
- [] Documentación actualizada
=> Add two colours to PaymentVaultViewController

.github/pull_request_template.md
- Se agrega a template de PR validación de UX
Revisión
[] Todos los textos se encuentran localizables
[] No se introducen warnings al proyecto
Testeo
=> Update PR template with UX validation

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardViewModelManager.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Fix #315 
- Se agrega un flag en CardFormViewController para poder ocular el botón de "Ver Promociones"
- Se agrega función para sacar los BankDeals cuando no es Argentina
Revisión
Testeo
=> Add showBankDeals flag in CardForm to disable deals

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/LoadingOverlay.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #313 
- Se fixea error encontrado por Wallet
- Se agrega Loading en Selección de Medio de Pago
Revisión
Testeo
=> Fixing Custom Loading

MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Base.lproj/Main.storyboard, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #255 
- Se arreglan los ejemplos de Objective -C
Revisión
Testeo
=> Fix StepExampleViewController examples

MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #324 
- Se corrije el formateo del amount
Revisión
Testeo
=> Mix of fixes

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #333 #334 
- Se resuelve el bug de porque no se entraba al formulario crédito/débito
- En grupos, se manda el card PaymentType que se selecciona al formulario
Revisión
Testeo
=> Fixes Mexico

MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #319 
- Ahora cuando tiene una sola cuota como opcion no pasa por la pantalla cuando elije tarjeta guardad
Revisión
Testeo
=> Default PayerCost with MP Card

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
- Se agrega la exclusión de dinero en cuenta el servicio de grupos
Revisión
Testeo
=> Exclusion de dinero en cuenta en el servicio de grupos

MercadoPagoSDK/MercadoPagoSDK/CardInformation.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTrackerDelegate.swift
Fix #342
- Agrego tags para que sea visible en objective c el listener de tracker
- Cambio el screen name de payment vault
Revisión
Testeo
=> - Fix Track Delegate for obj c

MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift
Fix #345 
- No se permite continuar sin llenar el DNI.
Revisión
Testeo
=> Fix de Pantalla IndentificationType 

MercadoPagoSDK/MercadoPagoSDK/HeaderCongratsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
Fix #341 
- Instrucciones no crashea con los nuevos cambios de decimales #324 
Revisión
Testeo
=> Fix instrucciones

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #331 
- Se agrego una vista nueva sobre la que se proyecta el loading para evitar que el mismo tape el nav bar generando un efecto visual no deseado y raro. 
Revisión
Testeo
=> Nav bar jump

.github/pull_request_template.md
=> Update PR template in development

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/xcshareddata/xcschemes/MercadoPagoSDKTests.xcscheme, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/UtilsTest.swift
Parte de #281
- Se agregan tests de Utils
- [ NA] Todos los textos se encuentran localizables
- [ NA] No se introducen warnings al proyecto
- [ NA] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
- [ X] No se agregan logs / prints innecesarios
- [ X] No se agregan comentarios basura
- [ NA] Testeado en BETA con emulador
- [ NA] Testeado en BETA con dispositivo
- [ X] Test unitarios OK
- [ NA] Documentación actualizada
=> Tests in Utils

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift
Fix #357 
- Se modifican los parametros de startPayerCost y startIssuers de MPStepBuilder
- [NA ] Todos los textos se encuentran localizables
=> Change MPStepBuilder

.gitignore
=> Update gitignore with MP framework

MercadoPagoSDK/MercadoPagoSDK/CardToken.swift
Fix #365 
- Se permite completar mes y año actual en el formulario de tarjeta
- Cambio 2
=> Fix expiration date

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift
Fix #364 
- Se reemplaza NavBar por Toolbar con botones de Anterior y Continuar en form de CC
=> NavBar replaced by Toolbar

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift
Fix #369 
- Se puede pegar un número de una tarjeta valida en el formulario de tarjeta
=> Guessing resolved for copy/pasting card numbers

MercadoPagoSDK/MercadoPagoSDK/CountdownTimer.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/String+Additions.swift
- Se sacan prints de la aplicacion
=> Sacar Prints

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.xib, MercadoPagoSDK/MercadoPagoSDK/CardFrontView.xib
- Se eliminan algunas constrains del xib de CardForm
- Se calculan las constrains por codigo
=> Remove constrains

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #392 
- Se realiza request a grupos aunque customer cards falle
- [NA] No se introducen warnings al proyecto
- [NA] No se agregan logs / prints innecesarios
- [NA] No se agregan comentarios basura
- [NA] Test unitarios OK
- [NA] Test funcionales OK
- [NA] Documentación actualizada
=> Search for groups even if customer cards fails

MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift
Fix #390 
- Se muestra Loading en pantalla completa
- [NA] No se introducen warnings al proyecto
=> Display loading properly in IdentificationVC

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostCardTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostCardTableViewCell.xib
- Se arreglan las constrains de CardAdditionalStep para ipad
=> Fix constrains In CardAditional Steps for iPad

MercadoPagoSDK/MercadoPagoSDK/IdentificationType.swift, MercadoPagoSDK/MercadoPagoSDK/Token.swift
Fix #402 
- Se cambia el campo id de toJSONString()  en Token y en IndetificationType
=> Fix Id in toJSONString() en Token

en_index.html, index.html
- Se arreglan snippets de codigo para f3
=> Add import MercadoSDK to snippets

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/ErrorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
- Se vuelve atras el cambio solicitado por la wallet que tapaba todo el navbar al momento de hacer un loading
- Se agrega la funcionalidad para que el callback cancel de la pantalla de error pueda ser inferido desde la creacion del flujo
=> Cambios wallet

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsRevampViewController.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPPayment.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/Payer.swift, MercadoPagoSDK/MercadoPagoSDK/Payment.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/MPPaymentTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/PayerTest.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/ExamplesUtils.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/MainExamplesViewController.swift
Fix #408, #417 
- Pagos con Blacklabel
- Se envia Payer dentro del POST de pago
- Se elimila el campo email en el body del POST de pago
- Se cambia el tipo de id en Pago de Int a String
=> Groups payer factory

MercadoPagoSDK/MercadoPagoSDK/CardToken.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
Reverts mercadopago/px-ios#439
=> Revert "- Fix ValidateSecurityCode"

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
- HotFix para bug reportado por wallet
- [NA] No se introducen warnings al proyecto
=> Hot fix for back button y PaymentVault

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/CardTypeTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/HeaderCongratsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionBodyTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/IssuerRowTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/LoadingOverlay.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostRowTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseItemDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/UIColor+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/UILoadingView.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/ViewUtils.swift, MercadoPagoSDK/MercadoPagoSDKTests/LoadingOverlay.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/ComponentTableViewCell.swift
Fix #432 
- Definición de colores solicitado por Wallet
=> Color definitions for wallet

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/Bin.swift, MercadoPagoSDK/MercadoPagoSDK/CardNumber.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Setting.swift, MercadoPagoSDK/MercadoPagoSDKTests/BinTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/CardNumberTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedData.plist, MercadoPagoSDK/MercadoPagoSDKTests/PaymentMethodTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/SettingTest.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples.xcodeproj/project.pbxproj
Fix #412 
- Se agregan campos faltantes de API a PaymentMethod
=> Payment method fields

MercadoPagoSDK/MercadoPagoSDK/InstructionReference.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Promo.swift, MercadoPagoSDK/MercadoPagoSDK/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDKTests/InstructionReferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentMethodTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PromoTest.swift
Fix #384 #321 #401 
- Promo.toJSON funcionando
- Se acualiza texto en RyC para redlink 
- Se cargan textos de referencia en instrucciones correctamente
=> Bug fixing

MercadoPagoSDK/MercadoPagoSDK/JSONHandler.swift, MercadoPagoSDK/MercadoPagoSDKTests/ExtensionsTest.swift
Fix #452 
- Se corrige que no se inviertan los valores de key y value en los parámetros para crear preferencia
=> Create pref fix

MercadoPagoSDK.podspec
Podspec updated with 2.2.27 version
=> Podspec updated

MercadoPagoSDK/MercadoPagoSDK/CountdownTimer.swift
Fix #178 
- Se mantiene un solo timer creado durante múltiples intentos de compra
=> Timer issue

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
Fix #461 
- Cambio 1
- Cambio 2
=> Desaparece la flechita de atrás antes de cargar grupos

MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift
Fix #475 
- Se cambia la parte de issuer del paramentro en getInstallments
- [ NA ] Todos los textos se encuentran localizables
- [ NA ] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
=> Fix parameter in getInstallments

MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
=> Remove decoration preference from App Delegate

.codecov.yml
=> Add codecov.yml

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDKTests/FlowPreferenceTest.swift
Fix #507 #471 
- Se añaden los tests a FlowPreference
=> Add flowPreference test

MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
- Se cambia el seteo de idioma del appDelegate
=> Fix AppDelegate

MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
- Bug Fix
- [] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
=> Enhancement

.codecov.yml
Fix #497 
- Se actualiza .codecov.yml a los nuevos cambios que subieron
=> Fix codecov.yml

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmPaymentTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ExitButtonTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Fix #523 
- Se vuelve a agregar la opcion de customizar RyC
- [] Todos los textos se encuentran localizables
=> Se re agrega la opcion de customizar RyC

MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Item.swift, MercadoPagoSDK/MercadoPagoSDK/Payer.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentPreference.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutPreferenceTest.swift
Fix #540 #535
- Se agregan setters para crear una checkoutPreference
=> Checkout prefernece

MercadoPagoSDK/MercadoPagoSDK/FlowPreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/FlowPreferenceTest.swift
Fix #542
- Se agrega disableDefaultSelectio() para habilitar o deshabilitar grupos
- [NA ] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
=> [WIP] Align flow preference with Android

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/MainExamplesViewController.swift
Fix #577
- Se arregla el cambio de color del navBar en RyC
=> Fix navBar Color in RyC

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Item.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift
Fix #583 
- Tests corren en el branch de refactor
=> Fix tests refactor

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift
Fix #586 
- Se puede pagar con tarjetas guardas en el flujo
- Cambio de orden de los pasos
=> Fix saved cards

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #585 
- Se arregla el flujo para poder pagar con account money
=> Fix account money flow

MercadoPagoSDK/MercadoPagoSDK/MPPayment.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift
Fix #407 
- Soporte de binary_mode en pagos
=> Binary_mode added for payments

MercadoPagoSDK/MercadoPagoSDK/ConfirmEmailTableViewCell.swift
Fix Wrong Validation
- SecondaryInfo falla si es un array vacío
=> Validate array properly in InstructionsVC

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPCustomCells.swift, MercadoPagoSDK/MercadoPagoSDK/MPCustomInflator.swift, MercadoPagoSDK/MercadoPagoSDK/VaultViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomInflator.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #597
- Se cambia las customRows
=> Refactor customRows

js/version.js
- Se actualiza la version del pod a la 2.2.10
=> Update documentation to pod 2.2.10

README.md
- Se actualiza la version del pod
=> Update README.md to pod 2.2.10

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPCellContentProvider.swift, MercadoPagoSDK/MercadoPagoSDK/MPCustomCell.swift, MercadoPagoSDK/MercadoPagoSDK/MPCustomInflator.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomCellProvider.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomCellProvider.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomInflator.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomInflator.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/SavedCardsTableViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultFormViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #605 #606 #607
- Se reemplaza Inflator por contentProvider para celdas custom en RyC
- Se resuelve navegación de grupos (falta verificar dinero en cuenta)
=> Custom rows and addCallback

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPXLoadingViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomItemTableViewCell.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomItemTableViewCell.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomItemTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #620 
- Se agrega llamada par aobtener un vc root de loading (requerimiento de wallet)
- Se setea opción seleccionada de grupos en caso de ir directo a RyC
=> Wallet reqs

MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se agrega un issuer al paymenData, para que no estalle cuando pagas en RyC
=> Fix examples

MercadoPagoSDK/MercadoPagoSDK/IdentificationCardView.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationCardView.xib, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #492 #468 
- Se modifico el tamaño de la tarjeta en el IdentificationViewController
- Se modifico el margen superior en la pantalla de grupos
=> Fix identification card size

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift
Fix #624 
- Se agrega site_id en llamada a grupos
- [ X] Testeado en BETA con dispositivo
=> Site_id in PaymentMethodSearch service

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift
Fix #654 
- Se permite deshabilitar RyC con FlowPreference
=> Deshabilitar RyC desde FlowPreference

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
Fix #589 
- Ocultar TyC en caso de que haya un AT
=> Hide TyC with AT

MercadoPagoSDK/MercadoPagoSDK/GatewayService.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationService.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/Token.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
- Se prioriza AT sobre PK para servicios de getaway
=> AT en Servicios a Getaway

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultFormViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #661 
- Se fixea un bug en los cambios de CFT en CardAdditionalStep
=> Fix CardAdditionalStep total bug

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
- Se vuelve a Selección de medio de pago al apretar "Cambiar medio de pago" en RyC
=> Start PaymentVault when changing payment method

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #672 
- Se arregla el flujo para que funcione con default installments
=> Fix defualt installments

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se muestra congrats en caso de que se ingrese a MercadopagoCheckout con paymentResult
=> Prior showCongrats (if there is paymentResult) in nextStep

MercadoPagoSDK/MercadoPagoSDK/AppDecorationKeeper.swift
Aplico el patron de diseño memento para keepear la decoracion de la app y apliucarla nuevamente.
=> Apply memento pattern

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/ReviewScreenPreferenceTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #688 
- Se agregan test de reviewScreePreference
=> Se agregan test de review screen preference

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift
Fix #691 
- Se arregla la altura de la celda de CFT en ryc
=> Fix CFT cell height in Ryc

MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift
- Se remueve flag de reviewAndConfirm 
- Se resuelve ir para atrás desde tarjeta guardada e ir a RyC
=> Remove RyC flag

MercadoPagoSDK/MercadoPagoSDK/PaymentResultScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Se cambian los addCells por setArrayCells para evitar agregar celdas duplicadas.
=> Se cambian los add cells por setArray de cells para evitar duplicados

MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift
Fix #700 
- Se arregla un force unwrapping en el failure del api call de installmnets
=> Remove force Unwrapping in installments apicall

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift
- Se deja finish() como step default
=> Finish como step default

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #697 
- Se agrega la funcionalidad de solo entrar en la pantalla de grupos cuando es necesario
- [] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
=> AutoSelección en grupos

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
- Se crean celdas dentro de la sdk tomando el content view de las celdas custom, en vez de tomarlas directamente
=> Fix Custom Cell

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Base.lproj/Main.storyboard, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
- Trackeo de pantallas de congrats
- Actualización de ejemplos en Steps
- [] Test unitarios OK
=> Tracking Payment Result screen. Update examples in objC

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
- Se soluciona el blink pusheando R&C, eliminando el stack de viewcontrollers en background
=> Clean nav stack fix

MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift
- Se actualiza screenName en paymentResultVC
=> screenName updated in PaymentResultVC

MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift
Fix #721
- Se despliega teclado al mostrar IdentificationVC
=> Pop keyboard in identification vc

js/version.js
=> Update sdk version to 2.2.11 docu

README.md
=> Change ReadMe to sdk 2.2.11

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Fix #745 
- Se fixea el crash al salir de la aplicación
=> Fix exit crash

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Fix #747 #742 
- Se muestra el loading al cambiar el medio de pago
- Se muestran los mensajes de error al intentar hacer un pago
=> FIX - Show loading in RyC changePaymentMethod

MercadoPagoSDK/MercadoPagoSDK/AppDecorationKeeper.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIScrollViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UIColor+Additions.swift
=> Status bar in RyC

MercadoPagoSDK/MercadoPagoSDK/GatewayService.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationService.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/PreferenceService.swift, MercadoPagoSDK/MercadoPagoSDK/PromosService.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift
Fix #765 
- Se mueven las URI de los servicios a ServicePreference
=> Move services URI to ServicePreference

MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MerchantServer.swift
Fix #767 
- Se envia el paymentAddiotionalInfo en MerchanServer createPayment()
=> Add paymentAdditionalInfo to createPayment

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDKTests/MPCheckoutTestAction.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift
- Se agregan tests de steps de casos básicos antes de iniciar refactor
=> MercadoPagoCheckoutVMTests before refactor

MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se agrega un minimo en el texto de summaryRow
=> Fix- Se agrega un minimo al description en Summary Row

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se agrega una propiedad "discount" a CheckoutViewModel
- Se agrega el objeto discount del paymentData a la creación del ViewModel de Revisa y Confirma.
=> Add discount to CheckoutViewModel

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountCoupon.swift
- Se agrega la row de descuentos en RyC
- Recalcular el total
- Si es un descuento de porcentaje, mostrar el monto que se descuenta
=> Se agrega la row de discount en Revisa y Confimra

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
- Se muestra el amount correctamente con los pagos off en RyC
=> Fix amount Off in RyC with discount

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/DiscountCoupon.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
=> Discount beta version

MercadoPagoSDK/MercadoPagoSDK/ConfirmEmailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsRevampViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift
Fix #800 
- Se carga el mail correctamente en instrucciones y en congrats
=> Fix email cell in PaymentResult

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.xib, MercadoPagoSDK/MercadoPagoSDK/IdentificationCardView.xib, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.xib
Fix #802 
- Se arreglan los problemas visuales en la pantalla de documento.
Quedaria asi la pantalla:
=> UX fixes to IndentificationViewController

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se elimina espacio en blanco en congrats en caso de que no se encuentre descuento
- [] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
=> Add height constraint in discount view in Congrats

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #821 
- Se muestran los ultimos 4 digitos en la pantalla de cuotas con una tarjeta guardada
=> Add last four digits to AdditionalViewController

.travis.yml
=> Add selected braches to .travis.yml

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
- Se agrega la opcion de recupero de pagos para el nuevo Checkout
=> Payment recovery

MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
- Se traduce a portugues textos faltantes
=> Add missing translations

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
Fix #838 
- Se muestran la cantidad de cuotas en el summary de Revisa y Confirma cuando son sin interes
=> Fix installment number not showing in Ryc

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
Fix #842
- No se muestra la celda de CFT cuando es una cuota
=> Remove CFT when installments is 1

MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se agrega la seleccion de Detail Coupon en AdditionalCardStep en caso de que corresponda
=> Add selection for Discount in Payer Cost

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
Fix #832
- Se cambia el tamaño de las celdas summary row en RyC
=> Change summary row heights in RyC

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
=> Fix summary height

MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmInstallmentsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDKTests/PayerCostTest.swift
- Se oculta CTF en la celda de medio de pago cuando no hay cuotas seleccionadas (1 cuota)
=> Hide CTF when have 1 nstallment

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
- Se muestra amount con descuento si lo hay para medios off
- [] Testeado en BETA con emulador
=> Display proper amount with discount

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift
=> Change wording in approvedBodyCell

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
- Se arreglan problemas con los loadings en tarjeta guardada y call for auth
=> Fix loading for wallet

MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift
Fix ##865
- Se agrega step de Validación de preferencia
=> Validate preference step

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #894 #893 
- Se mejora la manera de manejar los loadings
- Se mejora la manera de presentar los mensajes de error
- Se abre un metodo de goToRootViewController para los integradores
=> Fix MercadoPagoCheckoutLoadins and errors

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/xcshareddata/xcschemes/MercadoPagoSDKTests.xcscheme, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedResponse.plist
- Se agregan tests para MercadopagoCheckout
=> Add missing Tests

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/DiscountCoupon.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, MercadoPagoSDK/MercadoPagoSDKTests/DiscountCouponTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedData.plist
Fix #862 
- Se modificó el toJSON() del PaymentData.
- Se agregó el método toJSON() a la clase DiscountCoupon y el test correspondiente.
- [] Se incluyen cambios de UX ? se verificó que se vean bien tanto en iPhone SE y S6 : NA
=> PaymentData toJSON Method

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
=> Fix White Screen - betaVersion

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Fix #900 
- Se sacan las referencias strong de self en los callback en MercadoPagoCheckout
=> Remove self strong references in callbacks

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift
Fix #911 
- Se corrige el tamaño de la celda de cambiar medio de pago ON en RyC
=> Fix PaymentMethod RyC cell Height

MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.xib
Fix #918 
- Se saca el valor TEA de Revisa y Confirma
- Se cambia el tamaño de CFT a 24 pt
=> Remove TEA

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift
Fix #916 
- Se oculta la flecha en la vista de descuento que hay en la pantalla de un pago aprobado
=> Hide arrow in discount Congrats

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ContentTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ContentTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentResultViewModelTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/DineroEnCuentaTableViewCell.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/DineroEnCuentaTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #933 #715 
- Se saca lógica de PaymentResultViewController
- Se testea paymentResultViewModel
- Se resuelven bugs
=> Test payment result viewModel

MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift
Fix #937
- Se solucionan bugs en el payerCost toJSONString()
=> Fix PayerCost toJSONString

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #944 
- Se agrega una referencia estatica a la clase MercadoPagoCheckout a fines de mantener vivo el checkout activo, dado que el integrador podria no persistir una instancia del mismo y esto acarrea problemas de acceso a memoria,
=> Fix reference count cho - bug

MercadoPagoSDK/MercadoPagoSDK/Bin.swift, MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDK/MercadoPagoSDK/Token.swift, MercadoPagoSDK/MercadoPagoSDKTests/BinTest.swift
Fix #947
- Se arreglan los objetos toJSON para el plugin de hibrido.
=> Fix toJson

.github/pull_request_template.md
=> Add swiflint check to PR

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #958 
- Se setea el siteID al entrar con una preferencia hecha a mano
=> Change site with CheckoutPreference

.codecov.yml
- Se setea 50% min para mergear un PR
=> Se setea 50% min para mergear un PR

MercadoPagoSDK.podspec, PodTester/PodTester/MainTableViewController.swift, PodTester/PodTester/SettingsViewController.swift, PodTester/PodTester/SettingsViewModel.swift, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock, PodTester/Pods/Pods.xcodeproj/project.pbxproj
- Se actualiza la forma de levantar el checkout
=> Update Pod Tester

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, README.md
- Se actualiza la version de la sdk para sacar un pod
- Update README
=> Update version to 2.2.12

MercadoPagoSDK/MercadoPagoSDK/Customer.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift
Fix #1001 
- Se arregla los json de customer
=> Fix JSON in Customer

MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardsAdminViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardsAdminViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift
- Se cambia la logica de CardAdditionalViewModel
- Se agrega la opción extra al entrar sin tarjetas
- Se saca la llamada al servicio de la pantalla
=> Fix Card Manager

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/DecorationPreference.swift, MercadoPagoSDK/MercadoPagoSDK/FlowPreference.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutExtension.swift, MercadoPagoSDK/MercadoPagoSDKTests/FlowPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #978 #983 #982 
- Se mejoran los inits de MercadoPagoCheckout para Objective C
- Se mejoran los inits del Decoration Preference para Objective C
- Se agrega el deshabilitado de bankDeals en el flowPreference
=> Some changes for v3

MercadoPagoSDK.podspec
=> Update pod spec for 2.2.13

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/AddCouponViewController.swift, MercadoPagoSDK/MercadoPagoSDK/AddCouponViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/CallbackCancelDelegate.swift, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardsAdminViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardsAdminViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/CountdownTimer.swift, MercadoPagoSDK/MercadoPagoSDK/CouponDetailViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ErrorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/FlowPreference.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutExtension.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PromoViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDK/MercadoPagoSDKTests/FlowPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
- Se agregan seteos en Flow Preference, para configurar un máximo número de tarjetas guardadas a mostrar, o configurar mostrar todas. Si no se configura nada, o hay un error en la forma de configurar, se setea mostrar 3 tarjetas por default. Si se setean ambas opciones a la vez, tiene prioridad el seteo de ver todas las tarjetas.
- Se cambia la lógica del método ````getCustomerPaymentMethodsToDisplayCount() -> Int  ```` para que devuelva un valor teniendo en cuenta la configuración de la Flow Preference
- Se agregan tests de Flow Preference
- Se agregan tests de PaymentVaultViewController
`````objectivec
FlowPreference *flowPreference = [[FlowPreference alloc]init];
[flowPreference setMaxSavedCardsToShowFromString: FlowPreference.SHOW_ALL_SAVED_CARDS_CODE];
[MercadoPagoCheckout …
```
=> [Fix] Set Max Saved Cards to show

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
- Se vuelve a tener soporte a partir de iOS 8.0
=> Change pod iOS version to 8.0

MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, PodTester/PodTester/MainTableViewController.swift, PodTester/Pods/Pods.xcodeproj/project.pbxproj
Fix #1047
- Fix Prepaid Card Bug
- Update Pod Tester
=> Prepaid Bug

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, PodTester/Pods/Pods.xcodeproj/project.pbxproj
- Fix del back de revisa y confirma
=> Fixea el back de Revisa y confirma

MercadoPagoSDK/MercadoPagoSDK/Customer.swift
Fix #1061 
- Se corrige un bug en el customer toJson()
=> Fix Customer Cards Json

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostCFTTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostCFTTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/UIColor+Additions.swift, README.md
Fix #1064 
- Se agrega la pantalla de cuotas con CFT
=> Add confirm installments screen in V2

index.html
- Se actualizan los snippets de la docu con v3
=> Update snippets for v3

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
=> Fix token bug into development

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se excluyen los medios OFF en MLV, MLC, MCO
=> Se excluyen los medios OFF en MLV, MLC, MCO 

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #1088
- se fixea el bug de seleccion de otro medio de pago sin opciones
- se actualizan los test
=> Fix select other method

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, scripts/createPod.sh
Se actualiza la version para crear el pod 3.2.0
=> Update Version to 3.2.0

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #1097
- Se mueve el paso del error como primer paso del flujo
=> Fix error as first step

MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.xib
- Se modificó el campo donde se muestra el error en la pantalla de código de seguridad
=> Cvv Screen Error Message container updated

MercadoPagoSDK/MercadoPagoSDK/AddCouponViewController.xib, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDKTests/TrackStorageTest.swift
Fix #1100
- Se agrega track listener.
- Se agrega posibilidad de setear el viewController al que se popeara al finalizar mediante un método.
=> Wallet fixes

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/AddCouponViewController.xib, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKTests/TrackStorageTest.swift, scripts/createPod.sh
- Se traen los fixes hechos en master para wallet a develop
=> Update development with master

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/SecurityCode.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist
- Se modificó el método toJSON del objeto SecurityCode para ser compatible con el método fromJSON del mismo.
- Se actualizó la version del SDK
=> Fix SecurityCode to json

MercadoPagoSDK/MercadoPagoSDK/SecurityCode.swift
- Se modificó el método toJSON del objeto SecurityCode para ser compatible con el método fromJSON del mismo.
=> SecurityCode toJSON fix

MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.plist
- Se hizo un cambio en el plist de paymentMethod pata darle soporte a la tarjeta Maestro en la pantalla de tarjetas guardadas
=> CVV Screen Maestro Support

MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift
- Se corrigió el tamaño de la celda de CFT en la pantalla de Revisa y Confirma
=> Review & Confirm CFT row margins fixed

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift
- Se corrige el doble trackeo en algunas pantallas.
=> Check Double tracking

MercadoPagoSDK/MercadoPagoSDK/CustomService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedResponse.plist
- Se da soporte al modo gateway.
=> Gateway Mode

MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist
- Se cambia la uri de Tracking para tomar beta o v1 segun corresponda
- Se apaga Tracking
=> Disable Tracking. Add Uri to Track

MercadoPagoSDK.podspec
=> Remove esc from podspec

MercadoPagoSDK/MercadoPagoSDK/CardViewModelManager.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/ServicePreferenceTest.swift
- Se enciende la opción de processing mode hybrid.
- Se agrega lógica para ocultar el botón de "Mostrar Promociones" cuando el processing mode no es AGGREGATOR
=> [Feature] Hybrid processing mode

MercadoPagoSDK/MercadoPagoSDK/InstructionsViewController.swift
Fix #1140 
- Fix header bug in InstructionViewController
=> [Fix] header en intrucciones

MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTFingerPrint.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist
=> Enabled Tracking

PodTester/PodTester/MainTableViewController.swift
Fix #1142 
-  Se setea correctamente el site desde un JSON con una preferencia hecha a mano
=> [Fix] Se setea correctamente el site desde un JSON

MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift
- No se esta enviando correctamente el idioma en grupos ni instrucciones
=> [Fix] Bug with language in Payment Search in develop

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutExtension.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseItemDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ShoppingReviewPreference.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/ReviewScreenPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/ShoppingPreferenceTest.swift, PodTester/PodTester/MainTableViewController.swift, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock, PodTester/Pods/Pods.xcodeproj/project.pbxproj, PodTester/Pods/Target Support Files/MercadoPagoSDK/Info.plist
- Se agrega shopping preference para poder inferir títulos en la revisa y confirma, cambiar el cuantificador y el descriptor de monto a pagar por unidad.
=> Add Shopping Preference

MercadoPagoSDK/MercadoPagoSDK/ApiUtil.swift, MercadoPagoSDK/MercadoPagoSDK/GatewayService.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationService.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDK/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Token.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKTests/ExtensionsTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedResponse.plist
- Se agregan settings de servicios en el mpsdk_settings
- Se cambia la manera de formar parametros
- Se empieza a mandar access token y public key en los servicios de OP
- Se permite configurar los endpoints de issuers y de installments desde mpsdk_settings
=> [Feature] Change endpoints

scripts/change_podspec.sh
- Se agrega un script para publicar pod privado con ESC
=> Change podspec script develop

MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift
Fix #1156 
- Se deja de mostrar un loading al salir de Revisa y Confirma
=> Remove loading in confirmCallback in RyC

MercadoPagoSDK/MercadoPagoSDK/HeaderCongratsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift
Fix #1158
- Se fixea el bug que no permitia entrar a la pantalla de Call for Auth con una tarjeta de debito (es decir, sin payer Cost)
=> Fix call for Auth Debit Card

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/TrackingUtil.swift, MercadoPagoSDK/MercadoPagoSDKTests/SecurityCodeViewModelTest.swift
- Se agrega tracking al CAP de ESC
=> [Feature] Add tracking to ESC

CHANGELOG.md, MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, README.md
- Se hacen todos los cambios para el release 3.1.1
=> Release 3.1.1

MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift
=> Fix floating button bug.

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTFingerPrint.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/TrackStorageManager.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKTests/DateExtensionTest.swift
Fix #1172
- Se cambia el formato del timestamp a milisegundos
=> [Fix] Change timestamp to milliseconds

js/versions.js
- Se actualiza la documentacion para el nuevo pod
=> Change Documentation for 3.4.0

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTFingerPrint.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/TrackStorageManager.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKTests/DateExtensionTest.swift, README.md, scripts/change_podspec.sh
- Se corrige el boton flotante
- Se cambia el formato de la fecha para trackear
=> Hotfix 3.4.1

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTFingerPrint.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/TrackStorageManager.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKTests/DateExtensionTest.swift, README.md, scripts/change_podspec.sh
- Se agregan los cambios del hotfix 3.4.1
=> [Hotfix] 3.4.1

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionBodyTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultContentView.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentResultContentViewTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift
Fix #1151 
- Se cambia la manera de limpiar la data en el flujo. Se deja de borrar los datos recolectados en el back de las pantalla y se empieza a borrar en el update de la infromacion.
=> [Fix] Clear flows info

MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift
Fix #1178
- Se fixea el crash al tratar de pasar a JSON una tarjeta con dos settings
=> [Fix] Payment method toJSON()

js/versions.js
=> Update gh-pages for 3.4.3

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, PodTester/PodTester/MainTableViewController.swift
Se updetea la version a 3.5.0 y se modifica el podtester para ser funcional al caso de regre MG.
=> Update version 3.5.0

MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDKTests/MPPaymentTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDK/MercadoPagoSDKTests/PayerTest.swift
Fix #1209 
- Se saca el api call de identifications de la pantalla de documento y se agrega en el checkout
- Se actualizan los tests
=> [Feature] Remove identification api call

scripts/change_podspec.sh
- Se setea el flag de esc en modo testflight para wallet
- Se fixea un bug en el script
=> [Fix] Change podspec script for esc

index.html, js/versions.js
- En esta versión se agrega Bolbradesco, por lo que se cambia el mensaje de medios disponibles.
- Se actualiza la versión
=> [IO] Update to version 3.6.0

MercadoPagoSDK/MercadoPagoSDK/Address.swift, MercadoPagoSDK/MercadoPagoSDK/Payer.swift
- Se envia la información deñ address si vino en la checkout preference al pagar
=> [Fix] Send payer Address

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/HeaderCongratsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift
=> [Enhancement] Remove timer in V3

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock, PodTester/Pods/Pods.xcodeproj/project.pbxproj, PodTester/Pods/Target Support Files/MercadoPagoSDK/Info.plist, README.md
- Se actualiza la version de la sdk a la 3.6.1
=> Release 3.6.1

MercadoPagoSDK/MercadoPagoSDK/Tracker/TrackStorageManager.swift
Fix #1231 
- Se soluciona un crash con el tracking de timestamp
=> [Fix] timestamp

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, README.md
- Se cambia la version a 3.6.2
=> Release 3.6.2

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, README.md
- Se fixean bugs visuales para iOS 11
=> Development 3.6.4

scripts/change_podspec.sh
- Se cambia el script de pod de esc
=> [Fix] Add public source to ESC script

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.xib, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.xib, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/Podfile.lock, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock
- Se fixea el bug que no permitia ver el input en la pantalla de CVV y de Identification con iPhone X
=> Fix keyboard

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/PXHeaderViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PXReceiptComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXReceiptComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-CO.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-PE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-UY.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-VE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDKTests/PXResultViewModelTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj
Se agrega el comprobante de pago a la pantalla de resultado cuando el pago esta Approved
=> Add receipt to Payment Result Screen

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock, PodTester/Pods/Target Support Files/MercadoPagoSDK/Info.plist
- Se realizan los cambios necesarios para la lib de servicios 1.0.2
=> [Fix] Changes for lib 1.0.2

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock
- Se traen los cambios de master a develop
=> Merge with master

MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift
- Se returnea una imagen nil en ryc para que no crashee
=> Return nil image in ryc

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginNavigationHandler.swift
- Se añade la funcion nextAndRemoveCurrentScreenFromStack en PXPluginNavigationHandler para borrar del stack el currentViewController
=> [Fix] Plugin navigation

MercadoPagoSDK/MercadoPagoSDK/Hooks/PXCheckoutStore.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift
- Se agrega la función de init and mustshow a un payment method plugin
- Se agrega la opcion de tener una referencia al PXCheckoutStore desde el checkout
=> [WIP] [Feature] Add initialize and must show to PMP

MercadoPagoSDK/MercadoPagoSDK/Hooks/PXHookNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Se corrigen las transiciones
Se corrigen los loadings
Mejoras de navegacion en general
=> Fix Transitions

MercadoPagoSDK/MercadoPagoSDK/AddCouponViewController.swift, MercadoPagoSDK/MercadoPagoSDK/AdditionalStepTitleTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/AppDecorationKeeper.swift, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXHookNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/LoadingOverlay.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXDefaultTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXMeliTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXThemeObjects.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultTitleCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PromoViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ThemeManager+NavigationController.swift, MercadoPagoSDK/MercadoPagoSDK/ThemeManager.swift, MercadoPagoSDK/MercadoPagoSDK/UnlockCardTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ViewUtils.swift, MercadoPagoSDK/MercadoPagoSDKTests/PXBodyComponentTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PXResultViewModelTest.swift
=> Lint code. :)

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/MPXLoadingViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/WebViewController.swift
- Clean PaymentVaultViewController
- Remove Done ToDos
- Remove unnecessary overrides
=> Cleancode - v4

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginNavigationHandler.swift
Support for any congrats based on status and statusDetail
=> Agnostic finishPayment method.

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/BankInsterestTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CardAvailableView.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountDetailView.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/PXDefaultTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXMeliTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostPreferences.plist, MercadoPagoSDK/MercadoPagoSDK/PayerCostView.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/UIView+Additions.swift
- MPE bank interest cell activated
- Bank Interest Cell tint color fixed
- Identification Screen error loading fix
- AvailableCards Images updated
- Result Screen body bottom line fix
- Theme payerCost color fix
=> Minor UX Fixes

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MeliTheme.swift
- Swiftlint disabled
- MeliTheme as example ObjectiveC. Outside from SDK
=> Last Improvements v4

.travis.yml
Se desabilita travis en development
=> Dissable travis in development

.travis.yml
Reverts mercadopago/px-ios#1306
=> Revert "Dissable travis in development"

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CouponDetailViewController.swift, MercadoPagoSDK/MercadoPagoSDK/DisclaimerView.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountCoupon.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/PXErrorRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXHeaderRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsAccreditationCommentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsAccreditationTimeRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsActionRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsActionsRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsInfoRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsReferenceRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsReferencesRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsSecondaryInfoRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsSubtitleRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsTertiaryInfoRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXLayout.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXReceiptRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostView.swift, MercadoPagoSDK/MercadoPagoSDK/SummaryComponent.swift, MercadoPagoSDK/MercadoPagoSDK/TitleValueView.swift, MercadoPagoSDK/MercadoPagoSDKTests/DiscountCouponTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se soluciona el bug de la row de descuento aplicado
- Se crearon variables para todos los tamaños de fuente disponibles
- Se aplicaron los tamaños de fuente estáticos a todos los PXComponents
- Se modificó el DiscountCoupon para dar soporte a In-store
=> Enhancement & Fixes 

MercadoPagoSDK/MercadoPagoSDK/ItemsReview.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
- Se corrigieron las palabras de cantidad y precio unitario de la pantalla de RyC
=> RyC quantity fix

MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift
- Se solucionó el bug que hacia que la pantalla de pago rechazado tuviera un pequeño scroll.
=> In store UX FIX

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift
- Interfase TYPO corrected to Interface
=> Interfase TYPO fix

MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PXLayout.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodIconRenderer.swift
- Se agrega el fondo gris al icono del plugin de medio de pago en revisa y confirma
=> RyC plugin gray icon

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
- El botón de back ya no ejecuta el callback cancel seteado por el integrador.
=> Back button callback cancel fix

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Reverts mercadopago/px-ios#1320
=> Revert "Back button callback cancel fix"

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift
Se fixea el back de revisa y confirma.
=> Fix R&C Back

MercadoPagoSDK/MercadoPagoSDK/AppDecorationKeeper.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/ThemeManager+NavigationController.swift
- Fix white arrow when flow is closed.
- Fix swipe back gesture
- Improvements related to integrator navigation bar
=> Allow swipeBack on exit (if need) / Restore navigation integrator status

MercadoPagoSDK/MercadoPagoSDK/PXHeaderRenderer.swift
- Se cambia contentMode de la circleImage del header de congrats
=> Congrats URL Image Fix

MercadoPagoSDK/MercadoPagoSDK/PXResultConstants.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDKTests/PXResultViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/ReviewScreenPreferenceTest.swift
- Review And Confirm default texts fixed
- Congrats default texts fixed
=> RyC & Congrats default texts fixed

MercadoPagoSDK/MercadoPagoSDK/Hooks/PXCheckoutStore.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
=> Clean checkoutstore on exit

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se arregla el loading colgado que aparecía al pagar con medios off con una procesadora de pagos
=> Fix bug with off payment methods

MercadoPagoSDK/MercadoPagoSDK/CardBackView.swift, MercadoPagoSDK/MercadoPagoSDK/CardBackView.xib, MercadoPagoSDK/MercadoPagoSDK/CardFrontView.swift, MercadoPagoSDK/MercadoPagoSDK/CardFrontView.xib, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.swift
- Se cambia la font del label de cvv a monospaciada
=> [Fix] CVV label

MercadoPagoSDK/MercadoPagoSDK/DiscountCoupon.swift
- Se agregó la variable campaignId al objeto DiscountCoupon
=> Add campaignId to DiscountCoupon

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se selecciona por default a un plugin de medio de pago si es el unico
- Se saca la opcion de cambiar medio de pago de ryc si hay un unico plugin de medio de pago
=> [Fix] Payment method plugin default selection

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se vuelve atras la logica de payment method plugin autoselection porque no funciona con el init de los pms actual de hoy en día. La solucion es crear un nuevo step en la maquina de estados que se encargue de inicialisar los plugins y luego de eso ir a grupos a buscar los payment methods de la sdk.
=> [Revert] Payment Method plugin autoselection

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist
- Se actualiza la version del pod a 4.0.0.beta.11
=> Update pod version

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/CustomServer.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoServicesAdapter.swift, README.md
- Se creo el metodo createCheckoutPreference en la clase customServer
=> Custom Server Fix

MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift
- Se llama al deinit al salir de la pantalla de cuotas
=> [Enhancement] Leak in payer cost

MercadoPagoSDK/MercadoPagoSDK/InputComponent.swift
- Se pone weak los delegates de la pantalla, asi llamamos al deinit del view controller
=> [Enhancement] Leak PayerInfoViewController

MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift
- Se resuelve el bug que corta el texto de la descripción de la tarjeta de crédito en la pantalla de congrats.
- Se arreglan los test del paymentMethodDetail.
=> Fix - Congrats Cobranded - BETA 12

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift
- El init de los plugins se hace en otro step
- Funciona la autoseleccion de plugin en caso de ser unica
- Se fixea el bug donde se selecciona un medio de pago no siendo el unico
=> [Fix] Payment Method Plugins Auto Select

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXComponentizable.swift, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXHookComponent.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Hooks.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/PXCustomComponentContainer.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXThemeProperty.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginComponent.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockComponent.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockConfigPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockPaymentPluginViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedHookViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
- Se agrega el theme al render del componente
=> [Fix] Add theme to render

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist
=> Change version for 4.0.0.beta.12

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXComponentizable.swift, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXHookComponent.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Hooks.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/PXCustomComponentContainer.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXThemeProperty.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginComponent.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockComponent.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockConfigPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockPaymentPluginViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedHookViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentMethodPluginConfigViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
- Se manda el theme en el render de componentes
=> [Fix] Add theme in render components

MercadoPagoSDK/MercadoPagoSDK/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/PXInstructionsAccreditationTimeRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PXResultViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/ReviewScreenPreferenceTest.swift
- Se arreglan los bugs que no permitian ver la pantalla de congrats.
- Se arreglan los test unitarios.
- Se agrego la lógica necesaria para mostrar correctamente el nombre del issuer en la pantalla de congrats.
- Correcciones mínimas de UI. (Scroll indicator en congrats)
=> Templating/ryc Congrats FIXED

MercadoPagoSDK/MercadoPagoSDK/Utils.swift
- Se setea la fallbackImage si no nay url
=> Add fallback image if url is empty

MercadoPagoSDK/MercadoPagoSDK/PXCFTComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/PXSummaryFullComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResult.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
- Summary improvements
- CFT improvements
=> Improvements check UX

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se agrega la posibilidad de setear closures para reemplazar el show y el dismiss de nuestros loadings.
- Se agrega un estado para levantar el checkout express en la máquina de estados.
- Se levanta el sheet de Checkout Express desde MPCho.
=> Add custom loading closures.

MercadoPagoSDK/MercadoPagoSDK/PXReviewViewController.swift, scripts/createPod.sh
- Se updetea el script de creacion de pod
- Se fixea el bug del valor opcional
=> Fix optional value & update Script

MercadoPagoSDK.podspec, scripts/change_podspec.sh
=> Add esc dependency version

MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
=> FIX - Bug - Hide decimal format for ,00

MercadoPagoSDK/MercadoPagoSDK/PXReviewViewController.swift
=> Fix memory leak ryc

MercadoPagoSDK/MercadoPagoSDK/AvailableCardsDetailView.swift, MercadoPagoSDK/MercadoPagoSDK/BankDeal.swift, MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Identification.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Hooks.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/NSDictionary+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostView.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginConfigViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchItem.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PromosTyCViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ThemeManager+NavigationController.swift, MercadoPagoSDK/MercadoPagoSDK/TitleValueView.swift, MercadoPagoSDK/MercadoPagoSDK/UIView+Additions.swift, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json
=> Swiftlint Phase I - Warnings from 480 to 390 - Phase I

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json
- El formulario de tarjeta deja de ser lento en iphones viejos
=> [Fix]  Slow card form

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist, scripts/change_podspec.sh
=> Update beta version for release

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/CardFormViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/JSONHandler.swift, MercadoPagoSDK/MercadoPagoSDK/MPLabel.swift, MercadoPagoSDK/MercadoPagoSDK/MPTextView.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PXBodyRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PXImageService.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXTermsAndConditionView.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResult.swift, MercadoPagoSDK/MercadoPagoSDK/PromoTyCDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/Regex.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTFingerPrint.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
- Down to 45 warnings swiftlint
=> Swiftlint 40 warnings

MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
- Se actualiza en la aplicación de ejemplos un cambio de variable
=> Fix objc example app

MercadoPagoSDK/MercadoPagoSDK/PXThemeObjects.swift
- Se hicieron los cambios necesarios para que los primary buttons y secondary buttons usen la fuente custom del theme.
=> fix buttons fonts

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
- Se agrega un return en el finishFlowCallback, esto evita que se vuelva al root view controller
=> [DON'T MERGE] Fix finishFlowCallback

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MPPayment.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Se agrega el campaing_id para hacer el pago.
Se fixean los pagos con medios off y descuentos
=> Fix discount payment method off

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CongratsRevampViewController.swift, MercadoPagoSDK/MercadoPagoSDK/FooterTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXTimerManager.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
=> Add timer and redirect features for CDP over v2.2.11

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/PXCloseLinkAction.swift, MercadoPagoSDK/MercadoPagoSDK/PXNotificationManager.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m
Se agrega el unsuscribe del Notification Center, cuando finaliza el checkout.
=> Fix unsuscribe notification

MercadoPagoSDK/MercadoPagoSDK/CurrenciesUtil.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift
Jira: https://mercadolibre.atlassian.net/browse/CONV-12
=> v3 - Currency Venezuela

MercadoPagoSDK/MercadoPagoSDK/CurrenciesUtil.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift
Jira: https://mercadolibre.atlassian.net/browse/CONV-12
=> v4 - Currency Venezuela

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlowViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXFlow.swift
- Se agrega un PXFlow y se implementa en One tap
=> Add PXFlow interface

MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift
@demtej Dejo el PR del fix sobre develop. Para que ya quede sobre la v4 futura.
Pero deberían alinearlo y replicar el fix sobre el tag/branch del que saquen la prox beta. O beta-fix.
=> Fix instore congrats render after deeplink

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlowViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemComponentProps.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemContainerView.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXTheme.swift, MercadoPagoSDK/MercadoPagoSDK/ThemeManager.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se agrega el componente de item de one tap
=> Item one tap

MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemContainerView.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift
- Se centra el precio y la flechita en el medio de la pantalla
=> [Fix] One tap item component

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+Summary.swift
- Item arrow without transform
- Payment method with proper margin
- Summary viewModel method. 
- Summary MLModal without title
=> OneTap v2 / Minor improvements

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Base.lproj/Main.storyboard
- Se deja de llamar a showNavBar al hacer back de grupos
- Se elimina código deprecado de MercadoPagoUIViewController
=> Fix back navigation bar bug

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift
- Se sacan los valores defaults que se le agregan a cuotas si no vienen del servicio
=> Remove default values in payer costs

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlowViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift
- Se sacan los valores de cuotas por default al venir nil del servidor
- Se agrega el paso de tokenizacion de tarjetas con ESC en one tap
=> Fixes in one tap to develop

MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlowViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemComponentProps.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemContainerView.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXBankDealDetailsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXBankDealsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXUIImageView.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift
- Se introducen los cambios de descuento en el componente del item
- Se corre swiftlint
=> Add discount to item one tap component

MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemComponentProps.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift
- Se achica el monto total al ser un precio largo
- Se agrega la opcion de poder setear la flechita en el componente de item
=> Reduce font size with large amount in item one tap

MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapSummaryModalViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+PaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+Summary.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer+OneTap.swift
- Se agrega animacion de translation en Y/fade cuando aparece OneTap (sutil)
- Se soporta contenido centrado a nivel componentes
=> 3) OneTap v2 / Animation on appear and centered content view

MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow.swift
- Change one tap selection logic
=> Change one tap logic

MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow.swift
- Validates installment response in one tap
=> Validate installments

MercadoPagoSDK/MercadoPagoSDK/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXBodyViewModelHelper.swift
- Se muestra el descuento aplicado en la pantalla de resultado de pago.
- Se modifica la UI de la pantalla de resultado de pago.
=> Show discount in Payment Result

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoESC.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoESCImplementation.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/OneTapFlowViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/OneTapCard.swift, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se mandan los card id con esc y los plugins a grupos
- Se cambia la respuesta de one tap
=> Change one tap response

MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXDiscount.swift, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable_pt.plist
=> One tap discount disclaimer FIX

MercadoPagoSDK/MercadoPagoSDK/PXTotalRowRenderer.swift
- Se volvio para atras el fix que se hizo en la row flotante para el iPhone X ya que eso trajo un bug en otros dispositivos.
=> rollback fix for iphone X

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift
- Fix de seteo de languange ante un string vacio. Si esto llega a pasar defaulteamos español
=> Fix set languange with empty string

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer+OneTap.swift, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se arreglan los margenes en el componente de payment method en one tap
=> Fix margins in One tap

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXBusinessResult.swift, MercadoPagoSDK/MercadoPagoSDK/PXDiscountDetailViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m
Fixeamos el guardado de ESC con business result.
Se agregan campos de payment status y payment status detail en Business Result.
=> Fix ESC business result

MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se cambia la version de la lib de servicios a la 1.0.13
=> Change lib services version to 1.0.13

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/Podfile, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/Podfile
- Se cambia la version de la lib de servicios
- Se corrige como se cambia del modelo de payer de la lib de servicios al payer de la sdk
=> Change service lib version

MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se actualiza la version de la libreria de servicios a la 1.0.2.1.
- Se agrega el campo "comment" al objeto de modelo CustomerPaymentMethod.
- Se agrega la lógica necesaria para mostrar el comment en la pantalla de revisa y confirma.
=> Asset management support

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/mpsdk_settings.plist
=> update version to 3.7.5

MercadoPagoSDK.podspec
=> Update Podspec dependencies

MercadoPagoSDK/MercadoPagoSDK/PXTermsAndConditionView.swift
- Se corrige el bug visual que tenia la row de terminos y condiciones de descuentos en el iPhone 8 Plus.
=> Hot Fix Discount terms and conditions row

MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift
Se remueve los subtitulos de los plugines en grupos.
=> Asset Management Support V4

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.xib, MercadoPagoSDK/Podfile, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se actualizo la version de MercadoPagoServices
=> MercadoPagoServices version bump

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.xib, MercadoPagoSDK/Podfile, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se actualizo la version de MercadoPagoServices
=> MercadoPagoServices version bump to DEVELOP

MercadoPagoSDK/MercadoPagoSDK/PXTotalRowRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXTotalRowView.swift
- Se arreglo el bug visual que tenia la celda flotante en la en el iPhone X
=> Fix iPhone X floating row 

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Core/PXPropertyStoring.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXSpruce/Animations/PXStandardAnimation.swift, MercadoPagoSDK/MercadoPagoSDK/PXSpruce/Extensions/PXSpruce+UIView+.swift, MercadoPagoSDK/MercadoPagoSDK/PXSpruce/PXSpruce.swift
@edentorres Nos juntamos así te lo explico y lo analizamos.
=> Add pxSpruce capability to disable animation per view

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, scripts/createPod.sh
Se agrega el fix de cargos extra.
=> Hot fix beta 32

MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable_pt.plist
=> Line break fix - Terms conditions

MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/Podfile, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
Se agrego el parametro "payerEmail" al servicio de campañas activas
=> PayerEmail parameter to getCampaigns service

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/Podfile, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock, MercadoPagoSDKV4.podspec
Tomi´s kMLNavigationBarBackgroundViewTag
MLUI 5.0
=> Fixed Beta 34 a DEVELOP

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
- Se agregan traducciones en el componente de item en portugues
=> [Fix] Traducciones en Revisa y confirma en portugues

MercadoPagoSDK/MercadoPagoSDK/PXTermsAndConditionView.swift
- Terms and Conditions view background color fix
=> Terms and Conditions view background color fix

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/Podfile, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/Podfile, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
Se actualiza la dependencia de la lib de servicios.
=> Update Services Version dependency

MercadoPagoSDK/MercadoPagoSDK/MoneyIn/MercadoPagoCheckoutViewModel+MoneyIn.swift
Corrige el cambio de medio de pago luego de un pago rechazado
- Cambio 1
- Cambio 2
=> Rejected payment fix

MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift
- Se agrega commit que fixea el tachado en congrats
=> Fix override font attr strikethroughStyle

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se elimina el binary mode del payment flow y se usa el binary mode de la checkout preference
=> Enhancement binary mode

MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Item.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
=> Changes in item for v4

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXLanguages.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Item.swift, MercadoPagoSDK/MercadoPagoSDK/Localizator.swift, MercadoPagoSDK/MercadoPagoSDK/MPPayment.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel+Hooks.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoServicesModelAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PXSites.swift, MercadoPagoSDK/MercadoPagoSDK/Payer.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentPreference.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se cambia la firma de la checkout preference para v4
=> Changes CheckoutPreference

MercadoPagoSDK/MercadoPagoSDK/Hooks/PXCheckoutStore.swift
- Se prepara ChoStore para Jazzy.
- Se hace internal todo lo de manejo de data
=> Cho store refactor

MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift
- Se agregaron los customs views de la pantalla de resultados a la vista body de la misma. De esta forma cuando se expanda el body las customs views quedaran centrados en la pantalla
=> Result View Controller Custom Views FIX

MercadoPagoSDK/MercadoPagoSDK/PXBusinessResult.swift
Se agrega la documentación para Business Result.
=> Business Result Documentation

MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift
Se agrega el seteo de card id para soportar el flujo de money in
=> Add Card id setter

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCost.swift, MercadoPagoSDK/Podfile.lock, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
Se agrega el llamado y posterior uso de payer cost para debit card
=> Fix Debit Card installment

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel+Plugins.swift
- Se arregla la lógica para mostrar la pantalla de configuración del payment method plugin.
=> Payment Method Plugin Step FIX

MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> 🚀Update version to 4.0.1 🚀

MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXDiscountConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXPaymentConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXPaymentResultConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXReviewConfirmConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoCheckoutBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXLanguages.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXLifecycleProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/PXLazyInitProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXGenericPayment.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentProcessorNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXCheckoutStore.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/PXAction.swift, MercadoPagoSDK/MercadoPagoSDK/PXBusinessResult.swift, MercadoPagoSDK/MercadoPagoSDK/PXCheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/PXItem.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentTypeChargeRule.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentTypes.swift, MercadoPagoSDK/MercadoPagoSDK/PXSites.swift, MercadoPagoSDK/MercadoPagoSDK/PXTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXThemeProperty.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodConfigProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentProcessor/PXPaymentProcessor.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentStatus.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/PXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/PXTrackerListener.swift
Se documentó todo lo publico. Solo quedaron un par de getters sueltos. Que no tiene mucho sentido al menos por ahora. (A menos que querramos tener un 100%) Ya que al ser getters ya son muy descriptivos.
Se adjunta screen con el % de Jazzy: (86% documented)
Para ver como quedó revisen el git io: http://mercadopago.github.io/px-ios/v4/
=> 📚Jazzy full Documentation 📚

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
=> Fix one tap

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
- Se soluciona el fix de vending con one tap
=> Fix vending with one tap

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
- Se fixea vending en one tap en v4
=> Fix vending with one tap in V4

MercadoPagoSDK/MercadoPagoSDK/UI/Card/IdentificationViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/Podfile.lock
Se fixea el back de identification view controller que estaba crasheando
=> Fix Back in Identification View Controller

MercadoPagoSDK/MercadoPagoSDK/Core/Managers/ResourceManager.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Protocol/PXLifecycleProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Models/MPPayment.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXFinantialInstitution.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIssuer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepCellFactory.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Cells/FinancialInstitutionTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Cells/IssuerRowTableViewCell.swift
- Se utiliza el Resource Manager para algunos resources que quedaron medios huerfanos.
- Mejoras minimas en modelos legacy que usaban force.
- Se oculta de la docu el mecanismo de ChangePayment Method - (nada que ver con este PR)
=> 🛠️Resources Manager - Improvements 🛠️

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MoneyIn/MercadoPagoCheckoutViewModel+MoneyIn.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentPreference.swift
Se agrega una Payment Preference default.
=> Add default payment preference

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewController.swift
- Se corrigen los bugs en las pantallas de One Tap y Result
=> Fix One Tap & Result View Controller

MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift
- Se corrige un set de la payment preference en la checkout preference
=> Fix set in checkout preference

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCampaign.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXDiscount.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIssuer.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXToken.swift
- Se agregan getters de los ids para que se puedan ver desde objective-c
=> Add id getters to PXPaymentData objects

MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift
Se fixea el bug que hacia que no se valide bien la fecha de expiracion de la preferencia
=> Fix Validate preference

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
Se corrigen fixes reportados por Tomi de instore
Se corrige la status bar de One Tap (Ahora es siempre de color negra, deafult)
=> Fixes Visuales

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIssuer.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayer.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXToken.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXTransactionDetails.swift
=> Add Objcmembers to Payment Data props

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
Se fixea el bug limpiando la lista antes de rearmarla.
=> Fix customer payment method duplicated

MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Localize/PXLanguages.swift
- Se agrega pt-br a la lista de idiomas soportados
- Se cambia la lógica de matcheo de idioma
- Se corrigen los crash al settear un idioma no soportado
=> Fix set in languange

MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKV4-esc.podspec
- Se hacen los cambios para la 4.0.7
=> Changes for 4.0.7

MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKV4-esc.podspec
Reverts mercadopago/px-ios#1645
=> Revert "Changes for 4.0.7"

MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDKV4-esc.podspec
=> Changes for 4.0.7 

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift
- Se soluciono el bug que afectaba el tamaño del titulo en la pantalla de business result.
=> Fix business result title size

MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift
- Se deja de usar lazy var en localizator
=> Remove lazy var in localizator

MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlowModel.swift
- Se cambia el orden para buscar el descuento en el init flow. Primero se busca el descuento y después se va a grupos
=> Change discount order in init flow

MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift
Desuscribe el checkout de las notificaciones cuando se llama al change payment method.
=> Unsuscribe attemp to close notification

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
- Se actualiza la data del payment flow al llamar a createPaymentFlow
=> Fix create payment flow

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Config/PXReviewConfirmConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterProps.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift
- Se solucionaron los problemas de las traducciones del summary
- Se soluciona el bug de RyC del iPhone X
=> Fixes iPhone X & Summary Translations

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXReviewConfirmDynamicViewsConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
- Se agrego la posibilidad de agregar custom views dinámicas en la pantalla de Revisa y Confirma
=> Dynamic views in Review and Confirm

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/Extensions.swift, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXDynamicViewControllerProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
- Se agrega la posibilidad de agregar view controllers dinámicos en lugares pre establecidos a lo largo del flujo.
=> Dynamic View Controllers

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXNavigationHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PaymentFlow+Screens.swift
- Se cambia la manera de borrar las dynamic views del stack
- Se cambia la manera de como se borra el PXCheckoutStore (TODO: Juan)
=> Change way of deleting dynamic views

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFeedbackGenerator.swift
- Se centralizó la lógica para ejecutar haptic feedback
=> One Tap- Feedback Generator

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethodSearch+Business.swift
Improvement provisorio. Para que onetap check este basado en el nodo de express.
A futuro, vamos a analizar y resolver si tiene sentido o no tener grupos disociado o no. Por ahora no queda disociado.
=> One tap state machine validation with express node check

MercadoPagoSDK/MercadoPagoSDK/Core/PXNavigationHandler.swift
- Se fixea el bug de PXNavigationHandler al usar xcode9
=> Fix xcode 9 bug

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIView+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
- Se hizo el styling para la aplicación de Mercado Pago.
- Se agrego el shadow a la imagen del header
=> ONE TAP - Mercado Pago styling

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift
@edentorres Quedó funcionando todo el flujo de pago correctamente.
Pero hay un update que tuve que hacer si o si. Despues charlamos el porqué. El de paymentOptionSelected
Sinceramente es muy malo todo el manejo que tenemos de CardInformation, CardInformationForm, es todo muy confunso. Pero quedo funcionando bien. (Necesitamos tomar desde cero todo ese flujo cuanto antes)
Aproveche y meti una mejora en la conversion de un plugin a payment method. Fijate en plugin.toPaymentMethod.
=> Payment for one tap

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIView+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/AccountMoneyCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/EmptyCard.swift
- Se centraliza la logica de las sombras
- Se arregla el layout de la tarjeta vacia
=> One tap/add card bug

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+OneTapResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/PXOneTapResultHandlerProtocol.swift
- Se fixea la autoseleccion de medios con tarjetas de usuario y plugines.
- Se agrega la funcionalidad de cambiar tarjeta.
=> Fix change payment method one tap

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable_en.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable_pt.plist, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift
- Se agregó la lógica para comunicar cuando se esta utilizando dinero invertido.
=> ONE TAP - Invested account money

MercadoPagoSDKV4.podspec
- Se agrega la configuración del subspec privado de ESC para MDS y Nightly.
- Se cambia el source del podspec privado para usar SSH en vez de HTTPS.
=> Changes in Podspec

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutServices.swift
- Se remueve el dismiss loading antes de mostrar el error, ya que al mostrar la pantalla de error sacamos el loading ahi
=> [Fix] Fix infinite loading en identification

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift
- Se agrega el card id al modelo de cards de one tap
- Se agregan más cambios
=> Fix bugs in tracking one tap

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Discount/PXDiscountDetailViewController.swift
- Se modifica la forma en la que se trackea la pantalla de descuentos de one tap
=> One Tap discount screen tracking fix

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift, MercadoPagoSDKV4.podspec
Se arregla bucle infinito en la revisa y confirma
=> Fixea problema en R&C de bucle infinito

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentsSelectorView.swift
- Se arreglo la linea en el selector de cuotas
=> FIX - One tap installment separator line

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
- Se esconde la flecha y se deshabilita el desplegable cuando hay una sola cuota
=> OneTap :: Hide arrow with one installment

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift
- Se fixea bug al seleccionar la tarjeta
=> Fix one tap cards

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
Tested ok con Juli lima de instore
=> Instore fix :: Review confirm config

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckoutBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift
=> Add verb support for money in

MercadoPagoSDK/MercadoPagoSDK/Core/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethod+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-CO.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-PE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-UY.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-VE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
Se implementa label de tiempo de acreditación para empatar funcionalidad con android
=> Accreditation time

MercadoPagoSDK/MercadoPagoSDK/UI/Xibs/PaymentSearchCollectionViewCell.xib
Se agrega un identificador para poder detectar la presencia del MainGroupScreen en los UI tests
=> Se agrega identificador en PaymentMethods cell

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> Release 4.4.1

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> Bump version

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewController.swift
=> Visual bugs fixing

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIdentification.swift
- Se fixea el bug que no validaba que los datos del payer esten incompletos
=> Fix identification bug with boleto

CHANGELOG.md, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIdentification.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewController.swift, MercadoPagoSDKV4.podspec
=> [Release] 4.5.2

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSplitPaymentView.swift
=> Minor UI fixes

.circleci/config.yml
=> Update CI for build with XCode 10.1 [ci deploy]

.circleci/config.yml
=> Update XCode version

MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift
- Rondea los bordes del secondary button en todas las congrats, en revisa y confirma y en las congrats de alta de tarejta.
=> Round button corners en PXFootercomponent

CHANGELOG.md, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckout+InitFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> Error event track fix v4.6.0

MercadoPagoSDK/MercadoPagoSDK/Core/PXLayout.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderRenderer.swift
=> Minor fixes

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayment.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable_en.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable_pt.plist, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResourceProvider.swift
=> Error screen - rejected by regulations

MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsInteractionRenderer.swift
Fix ABM-58
- Se dejó dinámico el height del código de boleto Brasil para evitar que se pierdan dígitos.
=> Fix bug código cortado en boleto Brasil.

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+ConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethodConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAmountConfiguration.swift, MercadoPagoSDKV4.podspec
- Se pisa el ID de la campaña y el descuento con el discount token para el amount configuration seleccionado al momento de hacer al pago
=> FIX - Discount Token

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXDiscount.swift, MercadoPagoSDKV4.podspec
=> expose coupon amount in obj-c

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/UI/WebViewController.swift, MercadoPagoSDKV4.podspec
- Se soluciona el crash que sucede cuando se melidata intenta trackear la pantalla de terminos y condiciones.
=> Terms and Conditions tracking crash fix

MercadoPagoSDK/MercadoPagoSDK/Models/PXCardToken+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Alamofire/PXIdentificationType+Validations.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIdentificationType.swift
Se agrega la validacion de CPF & CNPJ
=> Add validation for CPF & CNPJ

MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepViewController.swift
- Fix bottom row re-rendered error on viewWillAppear
- Refactor code structure
Commit fix: https://github.com/mercadopago/px-ios/pull/1795/commits/7bb20be2549cba9e7a4fc6ac4b95814308217d00
Commit refactor structure: https://github.com/mercadopago/px-ios/pull/1795/commits/e316a51ea2ae3300ebdfd309fb51933bd36e78db
After re-structure:
=> Fix & Refactor - AdditionalStep

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/MercadoPagoUIViewController+Tracking.swift
=> Fix invalid tracks

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m, MercadoPagoSDK/MercadoPagoSDK/Add_card/PXResultAddCardFailedViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Add_card/PXResultAddCardSuccessViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PaymentResult.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayment.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable_en.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable_pt.plist, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderComponent.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResourceProvider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se agrega la pantalla de error para el status detail "rejected_by_regulations"
- Se agrega la cruz para cerrar el flujo en las pantallas de congrats
=> FEATURE - Recuperos y Rechazos

MercadoPagoSDK/MercadoPagoSDK/Add_card/PXResultAddCardFailedViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Add_card/PXResultAddCardSuccessViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterView + Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderView + Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewController + Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModelInterface.swift
=> ResultViewController buttons tracking

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m
=> Compile fail

MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckoutViewModel+InitFlow.swift
=> Fix bug with checkout preference

MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift, MercadoPagoSDKV4.podspec
- Se cambia el numero de release
- Se fixea bug con default installments
=> Resolve default installments bug

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSplitPaymentView.swift
- Minor split payment view fix
=> Minor split payment view fix

MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift
- Change transaction amount to getRawAmount in payment data
=> Change transaction amount to getRawAmount in payment data

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSplitPaymentView.swift
- Se corrige un error en el color de fuente de la split payment view
=> FIX - Split Payment View

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSplitPaymentView.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift
- Fix visual del color del texto en onetap de split
- Fix del rawAmount
- Changelog
=> Release 4.7.0

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift
=> Fix discount split token

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXDiscount.swift
- Fix deserializing discount id as int instead of int64
=> Fix discount id

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
- No se muestra el CFT en One Tap cuando es una sola cuota
=> One installment CFT fix

CHANGELOG.md, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCampaign.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Discount/PXDiscountDetailViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/TotalRow/PXTotalRowBuilder.swift
=> FIX - Soldout discounts

MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXSplitConfiguration+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXSplitPaymentMethod.swift
-  Fix decimal precision and round to n digitss
=> [FIX] Fix decimal precision and round to n digitss

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> Release 4.7.3

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PaymentFlow+Screens.swift
- Fix dismiss loading with dynamic view
=> Fix dismiss loading dynamic view controller

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentProcessorNavigationHandler.swift
- Fix needToShowLoading esc
- Fix vending esc bug
=> Fix needToShowLoading esc

.fastlane/Fastfile, CHANGELOG.md, MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, README.md
Test release public with bitrise
=> Public RC - Bitrise

MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoCheckout+Tracking.swift
- Add split enabled to init track
=> Add split enabled to init track

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> Bump version 4.8.0

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/.swiftlint.yml, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift
=> Add swiftlint to proyect

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlowModel.swift
- Se agrega un nuevo initializer que permite que cualquiera que uste esta lib, pueda omitir el congrats del flujo Alta de Tarjetas.
=> Adding init for skipping congrats

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PaymentFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
=> Release 4.8.1

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+ConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift
- Se fixea el bug que autoselecciona siempre una cuota en tarjetas guardadas en grupos.
=> [Fix] payer cost bug with saved cards

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PaymentFlow+Screens.swift
=> Fix instore vending bug

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIImage+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PaymentResult.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/Controller/CardHeaderController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/AccountMoneyCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/View/CardView/CardView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/View/CardView/Front/FrontView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/View/CardView/Front/FrontView.xib, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/FSPager/FSPagerView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PaymentVault/PaymentSearchCollectionViewCell.swift
deshabilita el ultimo medio seleccionado frente a casos de high risk para flow one tap
=> Disabled one tap

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift
Add card broken flow fixes.
- Close button now returns when pressed
- New setter for site id (broken identification mask fix)
=> [Fix] add card flow fixes

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomComponentText.swift, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/Extensions.swift, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
- Se migra el proyecto de ejemplos de objective c a swift 4.2 asi funciona con el nuevo xcode
=> Migrate example objective c project to swift 4.2

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/MPXTracker.swift
- Se obtiene la version del pod desde el bundle
=> Change way of getting pod version in code

MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable_en.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable_pt.plist, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyComponent.swift
=> Insufficient amount wording update

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIImage+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/View/CardView/Front/FrontView.xib
- Fix for card screen image layout
=> card layout fix

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Tracking keys changed
- Congrats wordings updated
=> bump version 4.11

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift
- Agregar esc manager en el flow de alta de tarjeta, guardar el esc segun el PAN
=> [Feature] Add esc manager to add card flow

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
- Soporte para tap en header (merchant)
- Se prepara un poco el código para el manejo de taps separados. (Nuevos delegates)
=> Header tap support

MercadoPagoSDK/MercadoPagoSDK/Config/PXDynamicViewControllerProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
- Se soporta desde advanced config el dynamic VC para el subtitle de one tap
- Se aliena con android la semantica del enum
=> Support external vc for one tap subtitle as modal

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/UI/SecurityCode/SecurityCodeViewModel.swift, MercadoPagoSDKV4.podspec
=> Change esc cap tracking and bump version 4.12.1

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/Swift+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIImage+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Core/LogHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable_en.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable_es.plist, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable_pt.plist
Support for displaying charges in one tap screen
=> Charges / Summary Composer

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer.swift
-no transparency on summary rows
-swap order between charges and discount rows
=> new summary definitions

MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentTypeChargeRule.swift
New optional "detail modal" property added to charge rule
=> Detail Modal

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView+SummaryProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSummaryProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSummaryRowView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSummaryView.swift
Added gesture recognizer to summary rows tied to actions in the containing view controller
=> Link rows to view controller delegate

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIDevice+Extension.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantLayout.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSummaryRowView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderSizeManager.swift
One tap screen layout adapted to support the new summary configuration
=> Header layout adapted

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckoutBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Localize/PXCustomTranslationKey.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Screens.swift
- Changes in example to test feature
- Dismiss loading only in Loyalty scenario (skip ryc) - _Loyalty ya lo testeo apuntando al branch._
- Custom translations support objc ! - New method
=> Fix to enable loyalty integration

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Core/ESC/PXESCManager.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/MPXTracker.swift, MercadoPagoSDKV4.podspec
- Se cambia la version de la lib de esc
- Se manda el flow a la lib de esc
=> Add flow to esc

MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift
Objective: add new fields for tracking the checkout preference object
=> 1- New tracking fields

MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethod+Business.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentMethod.swift
Payment method service response updated to start receiving processing mode as a new field.
=> 8- Processing mode in pxpaymentmethod

MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Gateway.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
New gateway fields should be available to customize and use in open preference implementations as well.
=> 10- open pref exposed getters and setters

MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift
Added a new constant for the default proccesing mode and replaced all "aggregator" occurences with the new constant.
=> 11- aggregator as a constant

MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardFormViewController.swift
soluciona un crash al hacer back en la pantalla de cvv
=> Flip card fix

MercadoPagoSDK/MercadoPagoSDK/Core/PXNavigationHandler.swift
Ver post de worksplace: https://meli.facebook.com/groups/592333500947478/permalink/1280721122108709/
=> modalPresentationStyle for iOS13 support

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Session id fixes
- Card drawer lib added
- iOS13 support
=> Release 4.14

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.15

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayerCost.swift
=> optional processing modes in payer cost

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.15.1

MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift
- Se cambia la URL de payments
=> Nueva url de payments

MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift
=> add terms view to extended container

MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift
- Se agrega productId al endpoint de pagos y se corrige bug del "X-Idempotency-Key"
=> Se agrega productId como header al endpoint de pagos

MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckoutViewModel+InitFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift
- Se cambia la validación de preferencias
=> Preference validation

MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepViewModel.swift
- Se saca la tarjeta en la pantalla de cuotas para los casos en que se paga con mercado crédito (digital_currency)
=> Se saca la imagen de la tarjeta en la pantalla de cuotas

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethodConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PaymentVault/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PaymentVault/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PaymentVault/PaymentVaultViewModel.swift
=> Credits subtitle

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift
- Se diseña la tarjeta y se obtienen los textos a mostrar del modelo
=> Diseño de tarjeta de mercadoCreditos en oneTap

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/CreditsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/LinkablePhraseViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift
…ales
- Se crea CreditsViewModel para que el dto no interactue directamente con la vista
=> Se crea CreditsViewModel a partir del dto de credits

MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift, MercadoPagoSDK/MercadoPagoSDK/UI/WebViewController.swift
- Fix animated button
- Improvement webview modal iOS 13 presentation
=> iOS13 Animated button fix

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Credits
- iOS13 improvements
- Fix aspect ratio
- Fix CFT
=> Release [4.19.0]

CHANGELOG.md, MercadoPagoSDK.podspec
Ver milestone:
https://github.com/mercadopago/px-ios/milestone/44
=> Improvements for 4.20

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift
- Se resuelve la animación en One Tap cuando aparece y desaparece la row de split payment
=> One Tap - Split payment animation fix

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
Add collector id to checkout pref
=> Add collector id

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Services/Constants/PXApiUtil.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/CustomService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/DiscountService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/GatewayService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/IdentificationService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PreferenceService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PromosService.swift
=> (Enhancement) | Remove code dupes in Services

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
=> Add ring animation in new congrats

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusiness Components Delegates/CrossSellingItemData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusiness Components Delegates/PXCrossSellingItemData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se hizo la integración del componente de Cross Selling
=> CONGRATS - ML Business Cross Selling View integration

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+OneTapResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/PXOneTapResultHandlerProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift
- Se agregan los business components a la nueva congrats con el flujo de oneTap
=> Add businessComponents in new congrats with oneTap flow

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/PXCongratsTracking.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
=> Add new Congrats tracking

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+PaymentFlowHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentResultHandlerProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/DownloadAction.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCrossSellingItem.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXDiscounts.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXDiscountsItem.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXDownloadAction.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPoints.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPointsAndDiscounts.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPointsAndDiscountsAction.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPointsProgress.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/Points.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/CustomService.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountItemData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountsBoxData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDownloadAppData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXRingViewData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PointsAndDiscounts/PointsAndDiscountsViewModel.swift
- Se agrega el prefijo PX a todos los archivos nuevos.
=> CONGRATS - PX Prefix

MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Constants/PXApiUtil.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
- Se agrego el campaign id al API call de puntos y beneficios
=> CONGRATS - Campaign ID added to API call

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/PXCongratsTracking.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths+Events.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
=> Fix comments

MercadoPagoSDK/MercadoPagoSDK/Core/PXLayout.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/Cells/PXNewCustomView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se arregla el footer para que este pineado al bottom en caso de que el contenido no ocupe la pantalla completa
- Se agrega la linea divisoria al footer
- Se cambia el color de fondo de la imagen de la celda de PM y receipt
- Se agregue un min height al elastic header en congrats
=>  CONGRATS - UI Changes

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-CO.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-PE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-UY.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-VE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/pt.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift
- Se agrega la hora a la celda de receipt en la congrats
=> CONGRATS - Add time to receipt cell

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift
- Se saca la linea divisoria en el caso de business result
=> CONGRATS - Business Result Separator line removed

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
- Se hace la llamada a la api de puntos y descuentos solo para las congrats verdes.
=> Se llama al endpoint de puntos y descuentos solo para congrats verde

CHANGELOG.md, MercadoPagoSDKV4.podspec
-Congrats improvements
-Fix warnings and possible leaks
-Fix bug oneTap installmentsView
=> Release[4.24]

MercadoPagoSDK/MercadoPagoSDK/UI/Base/TextMaskFormater.swift
=> Fix bug rut Chile

MercadoPagoSDK/MercadoPagoSDK/UI/Base/TextMaskFormater.swift
- Se vuelven los cambios al tag 4.24.2 en el que el fix ya se había solucionado.
=> Se vuelven los cambios al tag 4.24.2 donde el fix ya estaba resuelto

MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAvailableFeatures.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXExperiment.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitDTO.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXVariant.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/MPXTracker.swift
- Se agrega el modelo de PXExperiments.
- Se trackean los experiments.
=> A/B Testing

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXExperiment.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXVariant.swift
- Se reemplaza el ID de PXExperiments y PXVariante de un String a un Int
=> HOTFIX - PXExperiment & PXVariant Id changed to Int

MercadoPagoSDK/MercadoPagoSDK/Services/Constants/ApiParam.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
Se requiere para que merchant grow team pueda segementar features mediante el flow name.
=> Add flow name to congrats request

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
- Se agregan los campos "order_id" y "merchant_order_id" a la PXCheckoutPreference
=> Order ID & Merchant Order ID

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
- Se agregan valores default a los nuevos parámetros del init de la checkout preference.
=> FIX - Checkout Preference

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.27

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Version bump & changelog [ci deploy]

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift, MercadoPagoSDKV4.podspec
- Se cambia el tipo de dato de la merchant order id y la order id
=> Fix - Order ID & Merchant Order ID

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
=> Pass keys and siteId to onetapviewmodel

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewControllerTransition.swift
Cambios en la implementación de PX, necesarios para que la animación de entrada/salida hacia MLCardForm funcione correctamente. (Mergear primero el PR del repo de MLCardForm) y luego este PR.
PR en MLCardForm: https://github.com/mercadolibre/card-form-ios/pull/6
=> MLCardForm - Implementation transition improvements

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
- Se cambia el valor default de max installments
=> FIX - Max installments

MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXItem.swift
- Se hace un fix para redondear el Double en el encoder del PXItem
=> Fix - Double rounded

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift
- Add leading and trailing constraints
=> Fix merchantView title

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.28.2

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/Cells/PXNewCustomView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/Cells/PXNewResultHeader.swift
=> Set MLUI font to congrats title and payment method

MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitSearchBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
- Se unifica el valor del product ID.
=> FIX -  Product ID

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.28.3

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentPreference.swift
- Se empieza a enviar y recibir el default card id al backend.
=> FIX - Default card ID fix

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.29.1

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift
- Agrego un contador para la cantidad de refrescos posibles de init despues de agregar una tarjeta nueva
=> Add count to refresh retries

CHANGELOG.md, MercadoPagoSDKV4.podspec
- MLCardForm update
- Added max retries for Init refresh
=> Release 4.30.1

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.h, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
Agregar check antes de ir a buscar los descuentos de que si es business payment el decorator tiene que ser approve
=> Congrats con descuentos

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/One Tap Summary Row/PXOneTapSummaryRowView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift
=> Set MLUI fonts to oneTap

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift
- Se corrige un bug que no permitia que se mostrara el campo "helpMessage" en la pantalla de congrats de business result
=> FIX - Business result help message

MercadoPagoSDK/MercadoPagoSDK/Config/PXDiscountConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Config/PXDiscountReason.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXText.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Discount/PXDiscountDetailViewController.swift
- Se agrega la posibilidad de enviar 3 campos de texto desde el backend para poder renderizar el modal del descuento agotado de forma dinámica.
=> Feature - Dynamic discount modal

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXESCStatus.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCustomOptionSearchItem.swift
- Se cambio la propiedad invalidateESC por un string con 3 valores posibles. Se dejo true como default para no cambiar el comportamiento actual, hasta que prenda el backend
=> Se cambio la propiedad que viene de backend

MercadoPagoSDK/MercadoPagoSDK/Core/PXLayout.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/CreditsExpectation/PXCreditsExpectationView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/Cells/PXNewCustomView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Add credits expectation view to new congrats
=> Add credits expectation view to congrats

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift
- Se usa el site id de la respuesta del /checkout y se deja de usar el site id de la PXCheckoutPreference
=> FIX - Site ID

MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoCheckout+Tracking.swift
- Se ignora el flag de prendido de ESC
- Se pone como valor default true al ESC enabled
- Se depreca el seteo del flag de ESC enabled
=> Feature - ESC Always on

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckoutViewModel+InitFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift
- Se borra el cogido legacy de los PM plugins en los flujos de One tap e Init
=> PM plugins removed from OneTapFlow & InitFlow

MercadoPagoSDK/MercadoPagoSDK/Models/PXDisabledOption.swift
=> Replace missing key

ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountItemData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountTracker.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountsBoxData.swift
- Se agrego el trackeo del component DiscountBox de MLBusinessComponents
=> Feature - MLBusiness Discount Tracker

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentsSelectorCell.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
- Se corrige un bug que evitaba que se actualizaran las cuotas correctamente luego de cargar una tarjeta nueva.
=> Fix - One tap update after card form

MercadoPagoSDK/MercadoPagoSDK/Config/External/FlowBehaviour/PXFlowBehaviourDefault.swift, MercadoPagoSDK/MercadoPagoSDK/Config/External/FlowBehaviour/PXFlowBehaviourProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Managers/PXConfiguratorManager.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se agrega un nuevo protocolo para poder trackear las pantallas de congrats
=> Feature - Congrats tracking protocol

CHANGELOG.md, MercadoPagoSDKV4.podspec
Changes:
- ESC Always on
- One Tap for new and white label users
- Consumer credits terms and conditions for MLB
- MLBusiness Discount Tracker
- Congrats tracking protocol
- Translations fixes
- Minor UI Fixes
=> Release 4.32.0 (#2138) [ci deploy]

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountItemData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountTracker.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountsBoxData.swift
- Se comenta la implementación del MLBusinessDiscountTrackerProtocol para poder salir subirse a mobile-ios
=> Fix - Discount tracker commented

CHANGELOG.md, MercadoPagoSDK.podspec
- One Tap for new and white label users
- ESC Always on
- Translations fixes
- Minor UI Fixes
=> Public Release 4.32.2

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountItemData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountTracker.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/MLBusinessComponentsDelegates/PXDiscountsBoxData.swift
- Restored discount tracker. 
- Modified touchPointId with `px_congrats` instead of `px-congrats`.
=> Uncomment of DiscountTracker

MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift
- Se elimina la posibilidad de setear "pt" como lenguaje y se remplaza por "pt-BR"
=> Fix - Brasil language fix

MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Payer/PXPayerComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Payer/PXPayerProps.swift
- Se elimina el boton que permite cambiar el CPF en la pantalla de revisa y confirma
=> Fix - Change CPF button deleted

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
- Se resuelve un bug que evitaba mostrar correctamente el beneficio ofrecido por el banco.
=> Fix - Cards benefits snackbar

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift
=> Fix translation in congrats

MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable.stringsdict, MercadoPagoSDK/MercadoPagoSDK/Translations/es-AR.lproj/Localizable.stringsdict, MercadoPagoSDK/MercadoPagoSDK/Translations/es-MX.lproj/Localizable.stringsdict, MercadoPagoSDK/MercadoPagoSDK/Translations/es-VE.lproj/Localizable.stringsdict, MercadoPagoSDK/MercadoPagoSDK/Translations/pt-BR.lproj/Localizable.stringsdict
=> Fix stringsdict

CHANGELOG.md, MercadoPagoSDK.podspec
=> Public Release 4.32.4

MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/Translations/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-AR.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es-VE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/Translations/pt-BR.lproj/Localizable.strings
=> Fix discount text translation and add babel keys

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.32.5

MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift
- Se agrega la fuente correcta al PXFooter
=> Fix - Footer font

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+TokenizationServiceResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Core/ESC/PXESCManager.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+TokenizationServiceResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlowModel.swift
- Se comenta la nueva funcionalidad de trackear el reason y detail del deleteESC
- Se hacen correcciones al flujo de guardado y borrado de ESC
=> Fix - ESC flow fixes

MercadoPagoSDK/MercadoPagoSDK/Core/ESC/PXESCManager.swift
- Se habilita el tracking del reason y detail del deleteESC
=> Feature - ESC reason tracking enabled

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+TokenizationServiceResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+TokenizationServiceResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/TokenizationFlow/TokenizationService.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/TokenizationFlow/TokenizationServiceResultHandler.swift
- Se modifica el lugar donde se hace el request de reset esc cap
=> HOT FIX - Reset ESC cap refactor

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift
=> Fix language

MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
=> Fix accessibility label

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift
=> Fix accountMoney accessibilityLabel

.circleci/config.yml, CHANGELOG.md, MercadoPagoSDKV4.podspec
- Accessibility
- Fix CallForAuth crash
=> Release 4.33.0

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+RemedyServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/RemedyService.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se quitaron datos hardcodeados
=> Fix recuperos service

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXCreditsDisplayInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXResultInfo.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
=> Hacer valores de ResultInfo opcionales

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+OneTapResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+RemedyServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/PXOneTapResultHandlerProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PaymentResult.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
Se arreglo el remedy de CVV, porque no enviaba las datos correctamente a la API
=> Fix CVV remedy

CHANGELOG.md, MercadoPagoSDKV4.podspec
- ODR support
- Accessibility improvements
- Fix remedy bug
=> Release 4.33.1

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXResultTextFieldRemedyView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
Hay que revisar las imagenes de ODR en carddrawer para este tamaño.
=> Add CardUI to CVV

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift
=> Fix bug GIN-1081

CHANGELOG.md, MercadoPagoSDKV4.podspec
- IFPE support
- Add Card to CVV Remedy
- Fix bug 1081
- Accessibility improvements
=> Release 4.33.2

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.33.3

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/RemedyService.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift, MercadoPagoSDKV4.podspec
- Se agrega flow a la llamada de remedies
- Se valida que paymentID no este vacio
- Se actualiza la version de Andes
=> Remedies small fixes

MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXContainedActionButtonRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
=> Fix tyc view

.circleci/config.yml, CHANGELOG.md, MercadoPagoSDKV4.podspec
- Add total amount for silver bullet remedy
- Add flow name to every request header. Remove flow name as remedies request param
- Fix tyc view
=> Release 4.33.5

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
=> Fix CardForm flowID value

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+RemedyServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se agregaron datos para tracking de remedies
=> Add trackingData

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+RemedyServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift
- Se arreglo un problema con un loading infinito al querer recuperar los remedies
=> Fix remedies loading

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Feature CoronaVoucher
- Fix loading issue
- Agregado de datos para tracking de remedies
- Fix CardForm flowID value
=> Release 4.33.6

MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
=> Fix card label

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se agrego el nuevo componente MLBusinessTouchpointsView
- Refactor Codable
=> Release 4.33.8

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Offline methods/PXOfflineMethodsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift
https://mercadolibre.atlassian.net/browse/PXN-1062
=> Fix bug 1062

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se corrigieron tracks invalidos (Melidata)
- Se quitaron clases en desuso
- Se corrigio el bug 1062
- Se corrigio el bug 1100
=> release 4.33.9

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore.swift
- Se envia el valor de si se usa o no seguridad
=> Feature - add security type

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Offline methods/PXOfflineMethodsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
- Se actualiza el monto de la transaccion a enviar al modulo de biometric
=> Update amount in biometric validation

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se actualiza el monto para la validacion de biometric
- Se agrego security type al PXCheckoutStore
- Se redujo el numero de warnings en xCode
=> Release 4.34.0

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se actualiza la congrats
- Se corrigio un bug al agregar una nueva tarjeta
=> Release 4.34.1

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Feature Highlight Installments
=> Release 4.34.2

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se agrego la sigla CNTFA para credits
=> Release 4.34.3

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleSwift/ExampleSwift/Controllers/CustomCheckoutViewController.swift, ExampleSwift/ExampleSwift/Storyboards/Base.lproj/Main.storyboard, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
=> Feature appium changes

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Fix discounts bug for pay-preference
- Appium improvements
=> Release 4.34.4

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Update paymentData with suggestedPaymentMethod
=> Fix silverBulletAmountToPay

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
=> Add product id

MercadoPagoSDK/MercadoPagoSDK/Tracking/MPXTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/PXTracker.swift
- Evitar pisar el tracking Listener si ya se seteo con el track Listener de PXAddons
=> Utilizar solo PXAddon tracker si existe

MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoCheckout+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCheckoutPreference+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentPreference+Business.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se hicieron cambios en los tracks
=> Mejoras de tracking

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Add ExpenseSplitView to congrats
- Fix silverBullet amount
- Use PXAddons tracking
- Remedies tracking changes
=> Release 4.34.6

MercadoPagoSDK/MercadoPagoSDK/Models/PaymentResult.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift
- La pantalla de rechazo cuando un seller no puede recibir pagos tiene un CTA con un wording incorrecto
=> Fix PXN-1104

MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDto+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se mejoro la legibilidad de unas funciones de tracking y se corrigieron unos tracks de remedies
=> Housekeeping

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
- Se corrigio el titulo para el remedy de silver bullet + cvv
=> Remedy title fix

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
=> Fix backoffice bug

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Discounts enhancements
- Melidata fix
- Remedy title fix
- Ifpe backoffice fix
=> Release 4.34.8

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Add new values to Pref additional info
- Deprecate Groups flow models
- Fix oneTap crash
=> Release 4.34.9

MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
- Se intercambiaron los campos de CVV en remedies
=> Swap textfield title and help texts

MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXCardSecurityCodeFormFieldProperty.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
- Se cambia el componente de textfield para la view de remedies, ya que la anterior no se visualizaba correctamente en iOS 14
=> Remedy textfield test

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
Se añaden los métodos correspondientes a la funcionalidad de remedy de la congrats, también se añade el método para añadir callback que esta ligado a la implementación de remedies, queda pendiente el testeo de esta funcionalidad cuando se utilice el builder en el flujo de checkout
=> [Congrats] Add remedy builder methods

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCongratsPaymentInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCongratsType.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXExpenseSplit.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
Se pasan muchos metodos del builder a que reciban un optional, se eliminan algunos booleanos que no eran necesarios y se alienean ciertas cosas con Android
=> [Congrats] Payment Congrats builder API alignment

ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift
Se cambian algunos metodos a internal, se borran cosas innecesarias como el seteo de callback en paymentCongrats
=> [Congrats] Remove unnecesary things, and change methods to internal

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MLBusinessAppDataService.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXBackUrls.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference+AdditionalInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se agrega backURL, redirectURL y autoreturn
=> Feature redirect url

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Feature CFT
- Add backURL, redirectURL and autoreturn
- Show discounts row for consumer credits
- Discounts row improvements
=> Release 4.35.1

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Valido que la url no este vacia
=> Check empty url

ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCongratsPaymentInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
- Se actualiza el PaymentInfo con nuevos datos.
- Se actualiza la testApp de objc para tener más ejemplos
=> Adding new fields to PaymentInfo

CHANGELOG.md, ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MLBusinessAppDataService.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Managers/ThemeManager.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/OneTapSummaryRow/PXOneTapSummaryRowView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXBackUrls.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXCongratsPaymentInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPayerCost+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference+AdditionalInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXCFTComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Payer/PayerCostCFTTableViewCell.swift, MercadoPagoSDKV4.podspec
=> [Congrats] Weekly rebase

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.35.2

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsExamplesViewController.h, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsExamplesViewController.m, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsUtils.h, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsUtils.m, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Models/PXCongratsPaymentInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentTypes.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXText.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXExpenseSplit.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
- Se agrega compatibilidad de algunas clases que no eran visibles para objc.
- Se divide un método que recibía 9 parametros (para configurar el string de medio de pago) por métodos más pequeños que tienen menos parámetros.
=> [Congrats] OBJC Compat

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.35.3

ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se redirecciona la congrats genérica a traves de PaymentCongrats
=> [Congrats] Payment Result Adapt to PaymentCongrats

MercadoPagoSDK/MercadoPagoSDK/Config/PXDiscountConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift
- Se corrige un bug con descuentos
=> Fix con descuentos

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/Core/Managers/ResourceManager.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardBackView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardFrontView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/IdentificationCardView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PaymentVault/PaymentVaultViewController.swift, MercadoPagoSDK/Resources/Xibs/AdditionalStepCardTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/AdditionalStepTitleTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/BankInsterestTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/CardFormViewController.xib, MercadoPagoSDK/Resources/Xibs/CardFrontView.xib, MercadoPagoSDK/Resources/Xibs/CardTypeTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/EntityTypeTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/ErrorViewController.xib, MercadoPagoSDK/Resources/Xibs/FinancialInstitutionTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/FrontView.xib, MercadoPagoSDK/Resources/Xibs/IdentificationViewController.xib, MercadoPagoSDK/Resources/Xibs/IssuerRowTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/PXCardSliderPagerCell.xib, MercadoPagoSDK/Resources/Xibs/PayerCostCFTTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/PayerCostRowTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/PaymentSearchCollectionViewCell.xib, MercadoPagoSDK/Resources/Xibs/PaymentVaultTitleCollectionViewCell.xib, MercadoPagoSDK/Resources/Xibs/PurchaseDetailTableViewCell.xib, MercadoPagoSDK/Resources/Xibs/SecurityCodeViewController.xib, MercadoPagoSDK/Resources/Xibs/TotalPayerCostRowTableViewCell.xib, MercadoPagoSDKV4.podspec
- Los xib estaban en el bundle y se referenciaban a la lib con el nombre MercadoPagoSDK. Al querer usar el podspec de MercadoPagoSDKV4 se rompia la referencia y hacia que crashee.
Pase los xib a resources y actualice las referencias.
=> Fix bundle for V4

MercadoPagoSDK/MercadoPagoSDK/UI/SecurityCode/SecurityCodeViewController.swift
- Fix bundle for SecurityCodeViewController
=> Fix bundle

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Fix discounts bug
- Fix bundle for V4
=> Release 4.35.4

MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepCellFactory.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AditionalStep/AdditionalStepViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AvailableCards/AvailableCardsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXXibRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardBackView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXError/ErrorViewController.swift
=> Fix bundle selection

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
=> fix issuerid

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.35.5

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se corrigio el issuer id que se envia al pago
=> Release 4.35.6

ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
Se disponibiliza a traves de payment congrats las funcionalidades re AutoReturn and Redirect
=> [Congrats] PaymentCongrats Redirect and auto Return

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsExamplesViewController.m, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsUtils.h, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsUtils.m, ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongratsTracking.swift
Se arma un solo objeto para el parametro de tracking properties en el builder de payment Congrats
=> [Congrats] tracking alignement with android

CHANGELOG.md, MercadoPagoSDKV4.podspec
- MoneyIn MLB en OneTap
- Remote assets para medios off
=> Release 4.35.7

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Offline methods/PXOfflineMethodsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
- Se corrigio un problema para moneyIn. Al fallar el pago y llamar a showerror despues de ingresar un cvv, no mostraba el toast ni dejaba reintentar el pago
=> fix show error

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Congrats desacopladas del checkout
=> Release 4.35.9

CHANGELOG.md, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/CongratsUtils.m, ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongratsTracking.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Tracking/TrackingPaths.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
=> [Congrats] Tracking path fixes

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXCongratsPaymentInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Quite los espacios vacios para reducir los warnings de swiftlint
=> Remove empty spaces

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se arregla el path para tracking de congrats
=> Release 4.36.0

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentTypes.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
=> Add online and offline payment methods to previously hardcoded arrays

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Fix an issue with ObjC allowing to set a nil preference
- Fix an issue with some payment methods trying to fetch instructions
=> Release 4.36.1

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer+OneTap.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
- Corregi los constraints para que el boton no se muestre arriba
=> Fix button location an view constraints

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Fix button location an view constraints
- Add whitespace in discount label
=> Release 4.36.2

MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore+Encodable.swift
=> Add merchantOrderId to payment body

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Add merchantOrderId to payment body
=> Release 4.36.3

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
=> Ordene un poco el ejemplo para que sea mas facil editarlo

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+RemedyServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MoneyIn/MercadoPagoCheckoutViewModel+MoneyIn.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+Screens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitDTO.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
- Ahora se muestra la card de credits en la pantalla de remedies
- Se corrigio el monto que se muestra en silver bullet
- Se corrigio que llame a remedies si el pago fue rechazado utilizando credits o account money
- Se corrigieron algunos warnings de swiftlint
- Se agregaron algunas funcs para eliminar codigo duplicado
=> fix remedies

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.36.5

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Config/PXDiscountParamsConfiguration.swift
-Add additional params for obtaining a discount.
=> Add additional discount params

MercadoPagoSDKV4.podspec
=> Make lib static

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Static lib
- Add additional discount params
=> Release 4.36.6

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Constants/ApiParam.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAutoReturn.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXButton.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPointsAndDiscounts.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXAndesButtonConfig.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterProps.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
=> Auto return improvements

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Autoreturn improvements
- Tracking fix (total_amount)
=> Release 4.36.7

ExampleObjectiveC/Podfile, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSheetViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapNewCardDto.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapSheetOptionsDto.swift
- Se agrega un DTO para soportar mostrar una bottomsheet para webpay chile.
El json vendria de la siguiente manera:
```
"new_card": {
"label": {
"message": "Agregar una tarjeta nueva"
},
"sheet_options": [ (optional)
{"card_form_init_type": "standard"(mandatory),
"title": { (mandatory)
"message": "Crédito", (optional)
"text_color": "", (optional)
"weight": "" (optional)
},
"subtitle": { (optional)
"message": "Hasta 6 cuotas", (optional)
"text_color": "verde", (optional)
"weight": "" (optional)
},
"image_url": "asset card" (mandatory)
},
{"card_form_init_type": "webpay_tbk",
"title":{
"message": "Agregar una tarjeta nueva de debito"            
"text_color":"",
"weight":""
},
"image_url": ""
}
]
},
```
=> Add sheetOptions dto

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapSheetViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapSheetOptionsDto.swift
- Se arreglo un error en el modelo y se ajustaron algunos tamaños de la vista de la sheet
=> Fix model an adjust sizes

CHANGELOG.md, MercadoPagoSDK.podspec, MercadoPagoSDKV4.podspec
Support WebPay cards payments
Fix crash adding a new card
=> Release 4.36.8

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/LocationService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift
- Se agregó un service para determinar si está habilitado el permiso de location
- Se envía el header X-Location-Enabled en los requests que obtienen descuentos personalizados
=> Added LocationService and X-Location-Enabled header

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Added location header to congrats
=> Release 4.36.9

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.37.0

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se quita grupos y los assets que ya no se usan
=> Release 4.37.1

.circleci/config.yml, CHANGELOG.md, MercadoPagoSDKV4.podspec
- Removed old CVV view
- Fixed a bug where the loading indicator wouldn't be dismissed
=> Release 4.37.2

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Add webpay for MLC
- Fix bundle version
- Removed unused classes, removed white spaces, moved files to the correct folder
- Using Loyalty Broadcaster
- Add merchant_order_id to congrats
=> Release 4.37.3

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/AnimatedButton/PXAnimatedButton.swift
after entering add card and leaving without adding a card the button allowed tap
=> Fix pay button

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Offline methods/PXOfflineMethodsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/Congrats/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
=> Fix remedy button

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.37.4

MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDisplayInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDto.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
- Se muestra el switch para tarjetas combo
=> feat: Showing switch for combo cards

MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+RemedyServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Offline methods/PXOfflineMethodsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDto+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentMethodConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitDTO.swift
- Identifying PaymentMethodConfiguration by methodId and typeId in addition to id to prevent duplicated items on a Set
=> chore: Identifying PaymentMethodConfiguration by methodId and typeId

MercadoPagoSDK/MercadoPagoSDK/Config/PXAdvancedConfiguration.swift
- Reverted escEnabled and expressEnabled from get-only mode
=> chore: Reverted escEnabled and expressEnabled from get-only mode

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderViewModel.swift
- Mergeo codigo duplicado y agrego un delegate para pasar el evento del switch
=> Add selection delegate and merge duplicated code

.circleci/config.yml
This PR configures our Git to only allow merges if the unit tests is successful on CI
=> Configuring CI

MercadoPagoSDK/MercadoPagoSDK/UI/SecurityCode/PXSecurityCodeViewController.swift
- Se deshabilita el campo de CVV mientras se realiza el pago
https://user-images.githubusercontent.com/54864543/109220735-140c0b00-7798-11eb-813f-b50b5e6e9e0f.mp4
=> Disable CVV fields while making payment

MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore+Encodable.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore.swift
- This pr adds a new propertie on `PXCheckoutStore` , for now it’s not gonna be feeded or used, it depends on future changes
=> Add a new propertie to PXCheckoutStore

ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSliderPagerCell.swift
- Si la tarjeta es AccountMoney o Hybrid se usa CardData vacío
=> fix: Stop showing balance for AccountMoney or HybridCard

CHANGELOG.md, ExampleSwift/ExampleSwift/Controllers/ViewController.swift
🚀Private Release - 4.37.5 🚀
- Fix cvv textField that allow typing after submit
- Add propertie validationProgramId on PXCheckoutStore to be sent on future requests
=> Bump version 4.37.5

ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj
- Replaced xcconfig file references
=> fix: Replaced xcconfig file references

MercadoPagoSDKV4.podspec
🚀Private Release - 4.37.6 🚀
- Add a method to allow users from PX get validationProgramId on PXCheckoutStore
=> [ci deploy]

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXRemedy.swift
Adds propertie `bottomMessage` on `PXRemedy`
=> Add new propertie on PXRemedy

ExampleSwift/ExampleSwift/Controllers/CustomCheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDto.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXSecurityCode.swift
Adds a extra validation to see the necessity to ask user for cvv
=> CVV Validation

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitSearchBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
- Se agrega feature flag de tarjeta híbrida
=> Feature flag hybrid

MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore+Encodable.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
- Change validationProgramId coding key
- Filter benefits ony for credit_card
=> Fix validation program checkout

MercadoPagoSDK/MercadoPagoSDK/Flows/3DSFlow/ThreeDSService.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+ThreeDSServiceResultHandler.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift
- Passing cardHolderName to authorize3ds
=> Feature: 3ds adjustments

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> feat: Bumped version to 4.37.9

ExampleSwift/Podfile, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXCardDisplayInfoDto.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapDto.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapOfflineCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/TemplateCard.swift
Showing PIX on One Tap
Ask me for the mock
=> Feature - Implementing Pix in One Tap

MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/TemplateCard.swift
Fix 
Changed protocols to new MLCardDrawer version
=> Fix - Conforming to new protocols

CHANGELOG.md, ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj, MercadoPagoSDKV4.podspec
🚀Private Release - 4.39.2 🚀
- Conforming with old CardDrawer protocol
🚀Private Release - 4.39.0 🚀
- Pix payment
=> Release 4.39.3

CHANGELOG.md, MercadoPagoSDKV4.podspec
🚀Private Release - 4.39.4 🚀
- Adjusting project to manage tracks in a new way
=> Bump version 4.39.4

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift
Removed force unwrap from tracking refactor
Ask me how to test
=> FIX - Removing force unwrap

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Added the new installments v2.1 component on OneTap
- Added support for the new MLCardDrawerV3 card types
- Improved ComboSwitch behaviour on small devices
Using example app with a payment method with installments
=> Release 4.40.0

CHANGELOG.md, MercadoPagoSDKV4.podspec
🚀Private Release - 4.41.0 🚀
- BCRA regulation
=> Update changelog and SDK version

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+AddRow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/Components/PXSummaryComposer+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXCustomCharges.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentTypeChargeRule.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitDTO.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitSearchBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDKV4.podspec
Now we are using charges that come from backend
Use a payer who is "Persona jurídica" on MLA and it should be applying the IDC charge from backend.
=> Feature: charges from backend

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAmountConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXInitSearchBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/PXServicesURLConfigs.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
Added taxFreeAmount and noDiscountAmount on PXAmountConfiguration for IDC Support on accountMoney
Use a MLA "Persona Jurídica" account as payer, it should be applying IDC tax to the transaction
=> Feature: IDC tax free amount

CHANGELOG.md, MercadoPagoSDKV4.podspec
=> Release 4.42.0

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/OneTapSummaryRow/PXOneTapSummaryRowView.swift
Fixing title label constraint, to respect value label, and not stay under this if larger than free space.
Use a large title label text, if it's all right it will end in `...`.
=> [FIX] - [PXN - 2233] - Ajuste constraints tittleLabel

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXTermsAndConditionViewDelegate.swift
No mercado crédito por exemplo, exibe os termos de uso acima do botão de pagar, os termos apresentam um texto em destaque e ao clicar nele abre o regulamento.
=> [FEATURE] - [PXN-2304] - Adding terms to RemedyView if needed

MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
to avoid using new remedies screens without tracking we decided to comment those changes and uncomment it when tracks are ready
=> Avoid using new remedies features

MercadoPagoSDK/MercadoPagoSDK/Core/PXLayout.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/AnchorType.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Dimension/AnchorDimension.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Dimension/AnchorSizeComposing.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Dimension/ComposedDimensionAnchor.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Position/AnchorPositioning.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Position/AnchorPositioningComposing.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Position/AnchorX.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Position/AnchorY.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/Position/ComposedPositionAnchor.swift, MercadoPagoSDK/MercadoPagoSDK/LaytoutExtension/UIView+LayoutHelper.swift
Adds a new layout extension to help with the implementation of ViewCode. Deprecates the current layout helper.
=> Layout extension to help with ViewCode

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Add the checkout_type field to the checkout request
- fix the infinite alloc/repeat of congrats content on each viewWillAppear()
- Added danger and swiftlint to the project
=> Release 4.50.3

CHANGELOG.md, MercadoPagoSDKV4.podspec
modified:   CHANGELOG.md
modified:   MercadoPagoSDKV4.podspec
=> Release 4.55.1

MercadoPagoSDK/MercadoPagoSDK/Builders/PXPaymentTypeChargeRuleBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapNewCardDto.swift
- Se agregaron nuevos campos al nodo `new_card`
=> (Added)[PXN-3306] - New payment method model support
