mercadopago/px-ios

MercadoPagoSDK/MercadoPagoSDK/AmountInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDK/MercadoPagoSDK/CardToken.swift, MercadoPagoSDK/MercadoPagoSDK/Cardholder.swift, MercadoPagoSDK/MercadoPagoSDK/Identification.swift, MercadoPagoSDK/MercadoPagoSDK/Instruction.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Issuer.swift, MercadoPagoSDK/MercadoPagoSDK/Payment.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/Promo.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCode.swift
- Fixes en funciones de toJSONString de Card, CardHolder, CardToken, SecurityCode, Promo e InstructionInfo
=> Fixes in toJSONString functions

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ApprovedPaymentBodyTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/AuthorizePaymentHeaderTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ExitButtonTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/InstallmentSelectionTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.xib, MercadoPagoSDK/Podfile, MercadoPagoSDK/Pods/MercadoPagoTracker/MPTracker/GATracker.swift, MercadoPagoSDK/Pods/MercadoPagoTracker/MPTracker/MPTracker.swift, MercadoPagoSDK/Pods/MercadoPagoTracker/MPTracker/PaymentTracker.swift, MercadoPagoSDK/Pods/Pods.xcodeproj/project.pbxproj, MercadoPagoSDK/Pods/Target Support Files/MercadoPagoTracker/Info.plist, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/ServicesExamplesViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
- Se agrega lenaguaje pt o es según el siteId seteado en applicación (y no según el idioma configurado en el dispositivo)
- Se determina la currency según el siteId y se remueve como parámetro en F2
=> Internalization

MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CongratsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Installment.swift, MercadoPagoSDK/MercadoPagoSDK/MPFlowBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentCongratsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentPreference.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentType.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/ExamplesUtils.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/ServicesExamplesViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/SimpleVaultViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/SimpleVaultFormViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
- Métodos en PaymentPreference toJSON & fromJSON
- Método (deprecado) startPaymentMethod con supportedPaymentTypes (compatibilidad con SDK anterior)
- Valores default en cuotas en PaymentPreference (compatibilidad con objective-c)
- startPaymentResult agregado : el método retorna congrats o instrucciones según el estado de pago. F3 adaptado a nuevo step de PaymentResult.
- Enum de congratsStatus compatible con objective-c 
Se cierran #94 y #95
=> Align methods signature

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/xcshareddata/xcschemes/MercadoPagoSDK.xcscheme, MercadoPagoSDK/MercadoPagoSDKTests/BaseTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/GuessingFormTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoTestContext.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoUIViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedResponse.plist, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift
- Fix de target de tests unitarios
- Manejo de concurrencia de rquests unificada en MercadoPagoService (target de tests) y de carga de elementos de UI en BaseTest.simulateViewDidLoad
- Reporte de coverage disponible en Xcode para tests unitarios
=> Test coverage

MercadoPagoSDK/MercadoPagoSDK/GatewayService.swift, MercadoPagoSDK/MercadoPagoSDK/Installment.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/PreferenceService.swift, MercadoPagoSDK/MercadoPagoSDK/PromosService.swift
Aquellos servicios que se comunican con backend (fury) deberían poder ser seteados a BETA o PROD.
La creación de tokens, cuotas disponibles, medios de pagos disponibles y bancos son servicios provistos por OP, por lo que no se testean en distintos ambientes.
=> Remove env urls for v1 services

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardViewModelManager.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDKTests/CardViewModelManagerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/GuessingFormTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockBuilder.swift
- Creación de CardViewModelManager
- Se movieron los objetos de modelo de CardFormViewController al CardViewModelManager
- Se movió lógica simple de negocio (como ya estaba en el VC) a CardViewModelManager
- Se movieron métodos de parseo de fecha a Utils
- Pasos siguientes: remover la lógica de negocios que aún queda. Utilizar CardViewModelManager en MPStepBuilder y MPFlowBuilder
=> Card Manager in CardFormVC

MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
- Fix Card.toJSON() validations
- Add securityCode nil validation to avoid Crash with parsing JSON to String.
- Replace nil with  NSNull for JSONSerialization purpose.
- Add    "NSString *mppayment = [payment toJSONString];" in CHO Test
=> Fix Payment JSONSerialization bug.

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalStep.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift
Fix #228
- Cambio 1
Se cargan los últimos 4 números de la tarjeta en CardAdditional Step con una tarjeta guardada.
- Cambio 2
=> Fix llenar tarjeta guardada en pantalla de cuotas

MercadoPagoSDK/MercadoPagoSDK/CardFrontView.swift, MercadoPagoSDK/MercadoPagoSDK/HeaderCongratsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/TermsAndConditionsViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
Fix #259 & #248 
- Mostrar dots en CVV label para customer cards
- Se fixea el bug de no mostrar animación de CVV para amex
- Se elimina espacio en amount para evitar el salto de linea 
[NA] Documentación actualizada
=> Fix dots for CCs in front and back card view. Instructions header space in amount.

.travis.yml, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/xcshareddata/xcschemes/MercadoPagoSDKTests.xcscheme
Fix #281
- Se verifica subdirectory de MercadoPagoSDK con proyecto xcode (en vez de raíz de repositorio de px-ios)
- Scheme de tests se hace público para acceso de Travis
=> Subdirectory added. Tests scheme shared.

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDK/MercadoPagoSDK/CardInformation.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodWithDescriptionCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchItem.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentOptionDrawable.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentSearchCollectionViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #330 
- Se cargan todos los elementos tanto de medios de pago del customer como los medios de grupos en una única sección en F2
Revisión
Testeo
=> One section in payment vault

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearch.plist, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearch.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentService.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PreferenceService.swift, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
Fix #167 #236 #322
- Se utiliza parámetro de default option de payment method para ir a grupos. Se autoselecciona en caso de que grupos retorne un nodo válido como default
- Se corrige nombre de asset para Telecomm
- Se muestras los assets para tarjeta de débito y prepaga
- Se corrige typo en mensaje de error cuando no hay conexión a Internet
Revisión
Testeo
[NA] Documentación actualizada
=> Default pm in groups

MercadoPagoSDK/build-fat-framework.sh
- Se agrega un script `build-fat-framework.sh` que genera un .framework estatico compatible con todas las arquitecturas
Revisión
[] Todos los textos se encuentran localizables
[] No se introducen warnings al proyecto
Testeo
=> Add script for generating fat static frameworks

.travis.yml, MercadoPagoSDK/MPLoadingView.m, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/xcshareddata/xcschemes/MercadoPagoSDKTests.xcscheme, MercadoPagoSDK/MercadoPagoSDK/Tracker/FlowTrackInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/MPTracker.swift, MercadoPagoSDK/MercadoPagoSDK/Tracker/PaymentTrackInfo.swift, MercadoPagoSDK/MercadoPagoSDK/UILabel+Additions.swift, MercadoPagoSDK/MercadoPagoSDKTests/BaseTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/GuessingFormTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/InstructionReferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MPStepBuilderTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MaskElementTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoContextTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoTestContext.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoUIViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockCheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockPaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentCongratsViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentVaultViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/UtilsTest.swift
Fix #327
- Compila target de MercadoPagoSDKTests (se actualiza a Swift 3.0, se agregan clases de Revamp al target de MercadoPagoSDKTests)
Revisión
Testeo
[X] Test unitarios OK
=> Unit Test Target

MercadoPagoSDK/MercadoPagoSDK/CardToken.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m
Fix #436 
- Fix crash al validar manualmente el security code
=> - Fix ValidateSecurityCode

MercadoPagoSDK/MercadoPagoSDK/CardToken.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #436 
- Se fixea el crash de validacion manual de sec code con un cardtoken erroneo
=> Validation fix sec code

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardViewModelManager.swift, MercadoPagoSDK/MercadoPagoSDK/MPStepBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PromoViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/CardViewModelManagerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoService.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedResponse.plist, MercadoPagoSDK/MercadoPagoSDKTests/PromoViewControllerTest.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/MainExamplesViewController.swift, MercadoPagoSDKExamples/MercadoPagoSDKExamples/StepsExamplesViewController.swift
Fix #317 
- La visualización de Promociones depende de las promociones que vengan en API y no la PK en SDK 
- Se visualiza el título con el color de Fuente correcto
- Testeado con PK de MLA y MLB
=> Fix Promociones

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #465 #435 
- Se remueve el espacio entre el título de grupos y las otras celdas
=> Se remueve el espacio entre el título de grupos y las otras celdas

MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift
Fix #486
-  Se agarra el nombre real de un paymentMethod off en Ryc. Esto se mostraba mal en Mexico y en Peru
=> Se cambia el nombre del PaymentMethod en los pagos off en Ryc

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ConfirmPaymentTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, MercadoPagoSDK/MercadoPagoSDK/MPSDKLoadingView.m, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecrurityCodeViewController.xib, MercadoPagoSDK/MercadoPagoSDK/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Fix #474 #399 #410 
- Se vuelve a agregar el branch locale
- Se agrega un enum con todos idiomas soportados por la SDK. Ejemplo:
`MercadoPagoContext.setLanguage(language: MercadoPagoContext.languages.PORTUGUESE)`
=> Add locale brach to development

MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings, MercadoPagoSDKExamples/MercadoPagoSDKExamples/AppDelegate.swift
Fix #519 
- Se agregan traducciones de portugues faltantes
=> Fix traducciones portugues

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MPCustomInflator.swift, MercadoPagoSDK/MercadoPagoSDK/MPCustomTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostTitleTableViewCell.xib, MercadoPagoSDKExamples/MercadoPagoSDKExamples/MainExamplesViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomInflator.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomInflator.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.h, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Se arregla las celdas customisables para ObjC
=> Fix celdas customs en Objectve C

MercadoPagoSDK/MercadoPagoSDK/CheckoutPreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutPreferenceTest.swift
Fix #582 
- Validar que amount total sea superior a cero
=> Validate checkout preference amount

MercadoPagoSDK/MercadoPagoSDK/DecorationPreference.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift, MercadoPagoSDK/MercadoPagoSDKTests/DecorationPreferenceTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #509
- Se aceptan dos fuentes en la decorationPreference
=> Add light font to decorationPreference

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResult.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #638 
- Se puede empezar la SDK con un paymentResult
=> Add start with PaymentResult

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentPreference.swift
Fix #645 
- Se envia el paymentTypeId seleccionado al CardFormViewController en F3
=> Fix debit card flow

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #644
- Se agrega la opción de que el integrador pueda setear un paymentCallback que devuelve un pago hecho por la sdk y un callback simple que no devuelve nada para los casos que no hacemos el pago.
Ejemplo: 
```
[MercadoPagoCheckout setPaymentCallbackWithPaymentCallback:^(Payment * payment) {
NSLog(@"%@", payment._id);
}];
[MercadoPagoCheckout setCallbackWithCallback:^{
NSLog(@"Se termino el flujo");
}];
```
=> Add exit Callbacks

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
- Se puede ingresar a RyC con tarjeta guardada
- Se fixea error al seleccionar tarjeta guardada (salteaba ingreso de código de seguridad)
- Se limpia información de pago al iniciar la selección de medio de pago
=> Fix customer card selection when RyC is disabled

MercadoPagoSDK/MercadoPagoSDK/CardAdditionalViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostCardTableViewCell.swift
Fix #669 
- Se ven los 4 últimos dígitos de una tarjeta guarda cuando selecciona cuotas
=> Fix last four digits in cardAdittionalStep

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Fix #{677}
- Se oculta en cada VC que es pusheado la TabBar de la App del Integrador
=> - Hide TabBar in each pushed VC

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Diferenciar callback con paymentData del callback que se invoca al confirmar pago
```objc
[MercadoPagoCheckout setPaymentDataCallbackWithPaymentDataCallback: ^(PaymentData *paymentData) {
NSLog(@"%@", paymentData.paymentMethod._id);
}];
```
```objc
[MercadoPagoCheckout setPaymentDataConfirmCallbackWithPaymentDataConfirmCallback:^(PaymentData *paymentData) {
NSLog(@"Payment confirmed %@", paymentData.paymentMethod._id);
}];
```
=> Differ paymentDataCallback from confirm payment callback

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #696 
- Se pasan los paymentMethods que trae grupos al formulario de tarjeta asi no se buscan devuelta
=> Pasaje de paymentMethods a CardFormViewController

MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmInstallmentsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift
Fix #622 
- Setearle fuente custom Ligth a CFT y TEA
=> LightCustomFont Added to CFT & TEA

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift
Fix #710 
- Se muestra el precio de cada cuota correctamente en ApprovedBodyCell en congrats
=> Fix installment amount in approvedBodyCell

MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings
Fix #621 
- Se solucionó el bug que no permitía mostrar el link para acceder a Términos y Condiciones cuando el lenguaje estaba seteado a Ingles
=> Terms & Conditions in English Fixed

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift
Fix #718 #723 #725 
- Se arregla el flujo para que puedas volver a entrar a Revisa y Confirma con una tarjeta de debito
- Se arregla un problema de que si volvias a entrar al flujo con un paymentData para mostrar Revisa y confirma con una prefid con exclusiones (por ejemplo: Solo el nodo de tarjeta o solo el nodo de pagoOff) no iba a revisa y confirma. Iba directamente a grupos
- Fix bug con accountMoney
=> Fix flow with debitCard

MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #726 
- Se cambian todos los addCustomCell a setCustomCell
=> Cambiar todos los addCustomCell a setCustomCell

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
Fix #731 
- Se deshabilita el swipe en Revisa y Confirma
=> Se deshabilita el swipe en Revisa y confirma

MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.xib
Fix #737 
- Se arregla la altura de la celda de PaymentMethod en Revisa y Confirma
=> Change constraints in PaymentMethodCell in RyC

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj
Fix #728
- El tamaño de la celda se agarraba del xib y no de la función getHeight de MPCustomCell
=> Fix - Get custom cell height from MPCustomCell getHeight

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj
Fix #740
- Se evita hacer un double click cualquier nodo
=> Fix double click in gruops

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se agrega changePaymentmethodCallback a RyC en caso de que se requiera sobreescribir esta acción al intentar cambiar medio de pago en RyC. En caso que no se seteé, se sigue comportamiento default y se reinicia el checkout.
=> ChangePaymentMethod callback (temporary fix)

.codecov.yml, MercadoPagoSDK/MercadoPagoSDK/AppDecorationKeeper.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIScrollViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UIColor+Additions.swift
Fix #752
- Se agrega un loading en paymentSelectionScreen para mejorar la animación cuando esta pantalla se llama 2 veces seguidas.
=> Add loading to PaymentSelection Screen

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/SummaryRow.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #760 
- Se agrega la opcion de agregar items al summary de Revisa y Confirma
Ejemplo:
```
SummaryRow *summaryRow = [[SummaryRow alloc] initWithCustomDescription:@"Comisión BACEN" descriptionColor: UIColor.brownColor customAmount:20.0 amountColor:UIColor.redColor separatorLine:YES];
[reviewPreference setSummaryRowsWithSummaryRows:[NSArray arrayWithObjects:summaryRow, nil]];
```
=> Add summaryRow to ReviewScreenPreference

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Card.swift, MercadoPagoSDK/MercadoPagoSDK/CardInformation.swift, MercadoPagoSDK/MercadoPagoSDK/CardToken.swift, MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift, MercadoPagoSDK/MercadoPagoSDK/MPServicesBuilder.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.swift, MercadoPagoSDK/MercadoPagoSDK/SecurityCodeViewController.xib, MercadoPagoSDK/MercadoPagoSDK/Token.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #763 #762 #769 
- Se sacan los api calls de creación de token de la pantalla SecurityCodeViewController
- Se agrega un loading en cardAdditionalStep mientras se carga en pantalla
=> Remove services from SecurityCodeViewController

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #793 
- Se saca el espacio entre la celda de cupones y de los items en PaymentVault
=> Fix spacing in groups

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift
Fix #804
- Se saca la linea separadora en de la celda de cupones en la pantalla de pago aprobado
- Se saca la variable de cupones del paymentResultViewModel
=> Remove line in discountCell in PaymentResult

MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #806 
- Se saca el espacio extra entre el header de grupos y la celda de cupon
=> Remove extra space between header and discount

MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewController.swift
Fix #808 #809 
- Se saca el loadind de additionalStepViewController.
- Se agrega un callback cancel en cuotas y en issuers que borran los datos buscados del servicio y los datos seleccionados por el usuario.
=> Fix del flujo de back de AddiotionalStepViewController

MercadoPagoSDK/MercadoPagoSDK/PaymentResultScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/DineroEnCuentaTableViewCell.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/DineroEnCuentaTableViewCell.xib, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #813 
- Se agrega la opcion de setear una custom cell abajo de header en congrats
Ejemplo:
`    [PaymentResultScreenPreference setCustomApprovedSubHeaderCellWithCustomCells:[NSArray arrayWithObjects:subHeader, nil]];`
=> Add subheader customCell

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift
Fix #811 
- Se saca la linea extra del summaryRow
=> Remove extra line in summaryRow

MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/SummaryRow.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #819 
- Se añade la opción de deshabilitar el total en las summary Row
=> Add option to disable amount in custom summaryRows

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/Utils.swift
- Se remueve texto innecesario de "1x" en caso que el pago sea en una cuota única. También se oculta el label con el precio con interés para una cuota.
=> Remove 1x in RyC & Congrats

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CustomerPaymentMethod.swift
Fix #834
- Se hacen públicos los inits de CheckoutViewController
- Se hereda CheckoutViewModel de NSObject
- Se hace publico un init de CustomPaymentMethod
=> Fixes para recarga recurrente

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift
Fix #869 
- Se cambia el wording de dinero en cuenta de PaymentResultScreen
=> Change wording in approvedBodyCell

MercadoPagoSDK/MercadoPagoSDK/SecondaryExitButtonTableViewCell.swift
Fix #877 
- Se deja de poder seleccionar la celda que contiene el secodary button en Payment Result
=> Se deshabilita la seleccion de la celda de SecodaryButton en PaymentResult

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/NextStepHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Payment.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSearch.swift, MercadoPagoSDK/MercadoPagoSDKTests/CardViewModelManagerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewControllerTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MPCheckoutTestAction.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/NextStepHelperTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentMethodSearchTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift
Fix #695 #751 
- Se deja finish como step final siempre que se sale del flujo, ya sea cancelando o yendo hacia atrás (se guarda referencia de primer vc correspondiente a la sdk)
- Siempre que se entra con un paymentData completo se redirige a RyC
- Se reinicia FlowPreference en step de finish. De caso contrario al volver a entrar a la sdk se usa el último valor asignado anteriormente. @edentorres  @demtej 
- Se agregan tests unitarios para asegurar funcionalidad previa. Se agrega test de WalletIntegration que simula parte del flujo de Wallet
=> Cobertura + finish como último step

MercadoPagoSDK/MercadoPagoSDK/RejectedTableViewCell.swift
- En el caso de error de "cc_rejected_bad_filled_card_number", en la congrats se mostraba "El número de tu %0 es incorrecto." y faltaba reemplazar el %0
=> Fix missing parameter in congrats screen

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/CheckoutViewController.swift, MercadoPagoSDK/MercadoPagoSDK/FooterTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/HeaderCongratsTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/RejectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/SecondaryExitButtonTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentResultScreenPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/ReviewScreenPreferenceTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #694 #897 
- Se sacan las celdas custom como variables estaticas
- Se saca reviewScreenPreference y paymentResultScreenPreference como variables estaticas de MercadoPagoCheckout
=> Refactor de preferencias de pantallas

MercadoPagoSDK/MercadoPagoSDK/RejectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/RejectedTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/SecondaryExitButtonTableViewCell.swift
Cambié una constraint del content_title para que no se fuera de los márgenes, y cambie el number of lines a cero para que el texto caiga.
Le cambié el estilo de selcción a la celda de secondaryExitButton
Cambié la condición para que se muestre el content Title
=> Minor fixes

MercadoPagoSDK/MercadoPagoSDK/PayerCostRowTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/UILabel+Additions.swift
Fix #909 
- Se borro el texto con el total en la primera row de la pantalla de payer cost
=> PayerCost FirstRow description Deleted

MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-CO.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-MX.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-PE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-UY.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es-VE.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
Fix #920
- Se cambia el texto en Revisa y Confirma, "Pagaras $X en un cajero automatico de Cajero Automatico" por  "Pagaras $X en un cajero automatico de Red Link"
=> Fix bug en el wording de la celda Offline de RyC

MercadoPagoSDK/MercadoPagoSDK/CardsAdminViewController.swift, MercadoPagoSDK/MercadoPagoSDK/CardsAdminViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/PaymentResultScreenPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/ReviewScreenPreferenceTest.swift, MercadoPagoSDK/MercadoPagoSDKTests/WalletIntegrationTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/AppDelegate.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/StepsExamplesViewController.m
Fix #950
- Se setea la PK y AT desde el init de mercadopagoCheckout
=> Add PK and AT to MercadoPagoCheckout init

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift
Fix #953 
- Se agregan sets de language y site a MercadoPagoCheckout
=> Add language and site sets in MercadoPagoCheckout

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/en.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/es.lproj/Localizable.strings, MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
Fix #973 #974
- Se agregan los sets de strings pertenecientes a Perú, Venezuela, Uruguay e Idioma Inglés al podspect de manera de que el pod se cree con dichos lenguajes.
- Se agregan los textos "Si" - "No" a los archivos Localizables
=> Localizable Strings & Podspect

MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.xib
Fix #989 
- Se deja de mostrar el valor de TEA y se achica el tamaño de CFT según las normas
=> Remove TEA and change size of CFT

MercadoPagoSDK/MercadoPagoSDK/pt.lproj/Localizable.strings
- Se cambió el string que se muestra en portugués en RyC al pagar con dinero en cuenta
=> Corrected account money string

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoContext.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Base.lproj/Main.storyboard, scripts/createPod.sh
Fix #677 
- Se oculta el tabbar heredado de la app del integrador
=> Hide TabBar

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ApiUtil.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPago.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentCongratsViewController.swift
- Se entiende el status "499" que indica que un pago está en proceso, para dar el mensaje correcto al usuario.
- Se agregan constantes con los Status Detail.
- Se agregan constantes con status posibles de los requests en nueva clase ApiUtil
=> [V2][Feature] Added handling for payments in process

MercadoPagoSDK/.swiftlint.yml
- Se deshabilitan las nuevas reglas en swiftlint
=> Disable new swiftlint rules

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Fix #981
- Se decide no salir del flujo cuando los integradores nos setean un callback
```objective-c
[MercadoPagoCheckout setPaymentCallbackWithPaymentCallback:^(Payment * payment) {
NSLog(@"%@", payment._id);
[self.navigationController popToRootViewControllerAnimated:NO];
}];
```
=> Align payment callback

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDKTests/MercadoPagoCheckoutViewModelTest.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/ExampleUtils.h
Fix #979 
- Se añade la implentación de poder deshabilitar o habilitar la pantalla de resultados desde el flowPreference
=> Add support to disable payment result in FlowPreference

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
- Muestra el navigation bar al salir de la pantalla de payment result
=> Show navigation bar when exiting payment result

MercadoPagoSDK/MercadoPagoSDK/PaymentVaultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Fix #1045 
- Priorizar el servidor seteado en service preference para buscar cards del customer antes que las customer cards de grupos
=> Prioritize customer cards server before groups

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Payer.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewModelTest.swift
Fix #1050 
- Se limpia solo la data recolectada en el flujo al duplicar el paymentData en Revisa y confirma
=> Fix clean paymentData in ReviewScreen

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
Fix #1072 
- Se limpia el token al salir de identification y de componente de tarjeta
=> [Fix] Limpiar token al volver para atrás en el flujo

MercadoPagoSDK/MercadoPagoSDK/ApprovedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseDetailTableViewCell.swift, PodTester/PodTester/MainTableViewController.swift
- Se actualiza la advertencia de intereses bancarios para el site de MCO de acuerdo a los requerimientos de UX.
=> MCO Interest Warning Modified

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmPaymentTableViewCell.xib, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewModelTest.swift
- Se reemplazan los dos botones de confirmar el pago por uno solo "flotante" que acompaña al usuario a medida que se desplaza por la pantalla de revisa y confirma.
=> Floating Confirm Button

MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.xib
- A pedido de UX se activó el bounce vertical en la tabla de la pantalla de Revisa y Confirma
=> Review & Confirm tableview bounces

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel.swift
- Se corrige un error que impedia que se mostraran las tarjeta guardadas del usuario al momento de seleccionar un nuevo medio de pago luego de pasar por una pantalla de error
=> Saved cards fix in new selection

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseSimpleDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDKTests/CheckoutViewModelTest.swift
- La celda de productos quedaba muy chica al sacar el boton de confirmar. Se arregla el tamaño
=> [Fix] Product cell height in RyC

MercadoPagoSDK/MercadoPagoSDK/ApiUtil.swift
- Se cambia el codigo de error de invalid_esc de OP a 2107
=> [Fix] Se cambia el codigo de ESC invalido de OP

MercadoPagoSDK/MercadoPagoSDK/CustomService.swift, MercadoPagoSDK/MercadoPagoSDK/InstructionsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/ServicePreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedResponse.plist, MercadoPagoSDK/MercadoPagoSDKTests/ServicePreferenceTest.swift
- Se elimina el processing mode del servicio de payments
- Si el checkout no esta en modo agregador, en las pantallas de resultados, se oculta la celda en la que se le comunica al usuario que se le enviara un mail.
=> Remove Processing Mode from Payments Service

MercadoPagoSDK/MercadoPagoSDK/ErrorViewController.swift
Fix al crash de bugsnag: [Crash](https://app.bugsnag.com/mercadolibre/mercado-pago-ios/errors/59c0df6d249be30018c876a9?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open&event_id=59c908c2b0741d00183fb600)
- Cambio en la forma de llamar al valor del array para que no pida por un valor que no existe
=> fix crash bugsnag, index out of bounds

MercadoPagoSDK/MercadoPagoSDK/CardFormViewController.swift
Fix : Se escondia el textfield de numero de tarjeta atras del teclado hasta que el user tipeaba algun numero en iOS 11
- Se cambia UIKeyboardFrameBeginUserInfoKey po UIKeyboardFrameEndUserInfoKey para solucionarlo
iPhone 8:
iPhone SE:
=> Fix cardVC textfield iOS11

MercadoPagoSDK/MercadoPagoSDK/InstructionsService.swift, PodTester/PodTester/MainTableViewController.swift
Fix #1207 
- Se manda AT en el servicio de instrucciones
=> [Feature] Send AT in instructions api call

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift
Fix #1212 
- Se agrega sets publicos de PaymentResult, checkoutPreference y de PaymentData
- Se agrega un MercadoPagoCheckout.resume() para continuar con el flujo
=> [Feature] Add public sets to PaymentResult and PaymentData

MercadoPagoSDK/MercadoPagoSDK/AdditionalStepViewController.swift, MercadoPagoSDK/MercadoPagoSDK/IdentificationViewController.swift, PodTester/Podfile.lock, PodTester/Pods/Local Podspecs/MercadoPagoSDK.podspec.json, PodTester/Pods/Manifest.lock, PodTester/Pods/Target Support Files/MercadoPagoSDK/Info.plist
Fix #1237 #1238
- Se fixea el accesory view del input en Identification View Controller en iOS 11
- Se fixea la desaparicion de titulo en Additional Step View Controller en iOS 11
=> Catchup Tecnológico ( Fixes para iOS 11 )

MercadoPagoSDK/MercadoPagoSDK/Hooks/PXHookComponent.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedHookViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Hooks/FirstHookViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Hooks/SecondHookViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Hooks/ThirdHookViewController.m
- El integrador puede definir si mostrarlo o no, en funcion de la data que viene o lo que considere. Para eso se reemplazo en la interfase de Hook "didReceive" por "shouldSkipHook". Que retorna un BOOL y envia los parametros de HookStore.
- Se integro a los ejemplos de ObjcC
- Se integro a los Test
=> Capability to make hooks as optional in runtime

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift
Se remueven loadings innecesarios.
Se fixea el titulo de navbar que tardaba en mostrarse para dispositivos fisicos (no emuladores)
=> Remove loadings of R&C. Fix Navbar title.

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXComponentizable.swift, MercadoPagoSDK/MercadoPagoSDK/Hooks/PXHookComponent.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Hooks.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/PXCustomComponentContainer.swift, MercadoPagoSDK/MercadoPagoSDK/PXCustomComponentsHelper.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentResultScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockComponent.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockConfigPaymentMethodPlugin.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockPaymentPluginViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/MockedHookViewController.swift, MercadoPagoSDK/MercadoPagoSDKTests/ResultMockComponentHelper.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Hooks/FirstHookViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Hooks/SecondHookViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/Hooks/ThirdHookViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentMethodPluginConfigViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
- Se creo el protocolo PXCustomComponentizable al que se le pasa un PXCheckoutStore en la función render.
- Se adaptaron los componentes existentes para soportar PXCustomComponentizable.
=> Custom Component Store

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/PaymentResultScreenPreference.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
Se agrega un nuevo setter de imagen para el icono del header de la pantalla de resultado, para setearla mediante una url (string)
=> Set urlimage for Result Screen Preference

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoUIViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodPlugins/PXPluginNavigationHandler.swift
Se agrega la funcionalidad para poder hacer back al root de checkout en la pantalla de security code.
=> Back to Checkout root for Security Code Screen

MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift
- Minor fix de la celda del boton de confirmar pago en revisa y confirma
=> Confirm Button selectionStyle to none

MercadoPagoSDK/MercadoPagoSDK/PXBodyComponent.swift
- Se saca el issuerName temporalment en la congrats
=> [Fix] Remove issuer congrats

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckout+Screens+Hooks.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift
- Se pushean los view controllers del flujo (salvo el de la procesadora de pagos) con MercadoPagoChekcout.pushViewController en vez de hacer navigationController.pushViewController
=> [Fix] Change way of pushing view controllers

MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDKTests/PXBodyComponentTest.swift
- Se resuelve el bug que corta el texto de la descripción de la tarjeta de crédito en la pantalla de congrats.
- Se arreglan los test del paymentMethodDetail.
=> Fix - Congrats Cobranded

MercadoPagoSDK/MercadoPagoSDK/CheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/ConfirmAdditionalInfoTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountBodyCell.swift, MercadoPagoSDK/MercadoPagoSDK/DiscountDetailView.swift, MercadoPagoSDK/MercadoPagoSDK/OfflinePaymentMethodCell.swift, MercadoPagoSDK/MercadoPagoSDK/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXCFTComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/PXContainedActionButtonComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXContainedLabelRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXDefaultTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXItemComponentProps.swift, MercadoPagoSDK/MercadoPagoSDK/PXItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXTermsAndConditionView.swift, MercadoPagoSDK/MercadoPagoSDK/PXTheme.swift, MercadoPagoSDK/MercadoPagoSDK/PXThemeProperty.swift, MercadoPagoSDK/MercadoPagoSDK/PayerCostView.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethodSelectedTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/PurchaseItemDetailTableViewCell.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenPreference.swift, MercadoPagoSDK/MercadoPagoSDK/ReviewScreenViewController.swift, MercadoPagoSDK/MercadoPagoSDK/ThemeManager.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MeliTheme.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
Polish final de RyC ya chequeado con Max. 
Todos los componentes se integran correctamente y visualizan correctamente.
Se soporta Skin de Meli, de SinglePlayer y de cualquier otro integrador menor basado solo en primaryColor o un Theme entero. (Se testeo especialmente central de pasajes).
**Central Pasajes** _(Basado en setPrimaryColor)_
**SinglePlayer** _(Basado en DefaultTheme)_
**Meli** _(Basado en skin theme meli de instore)_
=> UI Final Polish Templating RyC with Themes.

MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDKTests/PXBodyComponentTest.swift
- Se actualizan los nombres de las variables de la clase PXPaymentMethodView para que estén alineados con las props del componente de payment method
=> PXPaymentMethodView variables RENAMED

MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/TestComponent.swift
Nuevo scenario:
- Si es mas de un item diferente se muestra "Productos"
- Si es solo un item se muestra el titulo del item (desde la pref de backend)
- Si el integrador hace el seter de la ReviewScreenPreference de productTitle, se anula todo lo anterior, y se muestra el titulo seteado en la ReviewScreenPreference independientemente de si es 1 producto o muchos productos.
=> Product title from Preference if need

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/PXBusinessResult.swift, MercadoPagoSDK/MercadoPagoSDK/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXCustomComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXLayout.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/CustomComponentText.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m
- Se agrega la posibilidad de setear vistas custom a mostrar en la pantalla de resultado cuando el pago es un business result.
- Se agrega el ejemplo
=> Add custom component to business restult. Add Example.

MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+PaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer+OneTap.swift
- Fix para adaptar payment method component de onetap a descuentos UI
- Se arregla el margen derecho del arrow de payment method one tap
- Se utiliza un nuevo metodo de viewModel que indica si hay que mostrar summary o no. En funcion de eso se hace tapeable o no el item component y se muestra/oculta su arrow. @edentorres
=> 1) OneTap v2 / PaymentMethod fixes for descuentos - Item arrow changes

MercadoPagoSDK/MercadoPagoSDK/One tap/UI/Item/PXOneTapItemRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapSummaryModalViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+ItemComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+PaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+Summary.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXPaymentMethodComponentRenderer+OneTap.swift
- Se crea lógica especial para decidir si se muestra el modal o no
- El modal de summary muestra la lista de items con su amountUnitario*unidad y su description (Si corresponde)
- El modal de summary permite que se le inyecte una UIView en el bottom. Eso se utilizará en descuentos.
- La logica de si se muestra summary + view de descuentos o solo view de descuentos dentro del modal ya quedó resuelta. @augustocollerone Fijate que en PXOneTapViewController quedo una función que retorna una UIView llamada `getDiscountDetailView()`. Ahí deberias crear tu vista con la info de descuentos. Con retornar la view ya estaría todo listo y se inyectaría automáticamente. (Con o sin summary segun corresponda automaticamente)
- Se corrige el margin del arrow de ItemComponent
- Se setea shouldShowArrow en …
=> 2) OneTap v2 / Summary Modal

MercadoPagoSDK/MercadoPagoSDK.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+PaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXTrackingUtil.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj
- Aproveche y metí lo de CFT aca también. No hice nada raro. Repliqué lo que ya veniamos "manejando" en otras pantallas. La sigla CFT esta totalmente harcoded y descentralizada.
- Se crearon los nuevos eventos. 
- Se refactorizo muy minor el manejo nuestro desde el lado de la sdk de la extension de tracking util. Haciendo un poco mas descriptivo todo con structs que agrupan la semantica. De todas maneras tenemos una gran dauda pendiente historica ahi, de unificar el repo de tracking y todo lo que ya sabemos.
- Se ejecuta el track event desde el viewModel para cada evento nuevo correspondiente.
Queda implementar:
- Llamar desde el controller al tracking method del viewModel al hacer back.
- Cuando este la row de descuentos terms and conditions. Llamar a el evento correspondiente que ya …
=> Onetap/v2 Metricas

MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutViewModel+Plugins.swift, MercadoPagoSDK/MercadoPagoSDK/One tap/UI/PXOneTapViewModel+PaymentMethodComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXBodyComponent.swift, MercadoPagoSDK/MercadoPagoSDK/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/PaymentMethod.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Se propaga el campo de descripcion de los plugins de medio de pago en la creacion del medio de pago correspondiente y se utiliza para mostrar el subtitulo en la celda de PM.
=> Add description to Payment Method plugin

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXLayout.swift
Como estamos usando navigation transparente, la content queda con mas contenido. Y al ser todo blanco, si bien esta centrado verticalmente, da sensación de que no lo esté. Por eso explicitamente en el Controller de OneTap, que sabe que tiene navigation trans, se le indica un -delta de margin al center.
=> OneTap fix, vertical aligment

MercadoPagoSDK/MercadoPagoSDK/Config/PXPaymentResultConfiguration.swift
- Fixea bug que hace que el titulo de la congrats se vea en otro idioma la primera vez que se corre el flujo
=> Bug idioma titulo congrats

MercadoPagoSDK/MercadoPagoSDK/PXComponentContainerViewController.swift
- Se arreglo el bug en la pantalla de RyC cuando el boton explota y transiciona hacia la pantalla de congrats.
=> Fix navigation bar explosion

MercadoPagoSDK/MercadoPagoSDK/Core/PXLifecycleProtocol.swift, MercadoPagoSDK/MercadoPagoSDK/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/PXResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/PXReviewViewController.swift, MercadoPagoSDKExamplesObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m
Nos vimos obligados a contemplar esta funcionalidad nuevamente. Es clave para MoneyIn por ejemplo.
Se resuelve de manera elegante y escalable. Quedando en el LifeCycle protocol que ya teniamos para informar salidas. Es un metodo opcional del LifeCycle. Si lo definen y retornan el bloque, ejecutamos ese bloque y no hacemos nada (solo trackeamos la action). Es optional, por ahora solo lo utilizaria moneIn. 
En Android harán lo mismo. Pero ellos salen del CHO por un callback, no mediante un protocolo. Nosotros tenemos un protocolo que dentro tiene un method con un callback. 
Por ahora se puso solo en Revisa y Confirma. Lo van a probar y si se necesita en Congrats efectivamente, se replicará el mecanismo.
=> 💸Change payment method capability 💸

MercadoPagoSDK.podspec, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist
- Soluciona el crash importando la sdk como podspec. Se agregan los xibs a los resources en el podspec
=> Add xibs to podspec

MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXBody/PXBodyComponent.swift
Se remueve la descripción del payment method para las pantallas de resultado de pago y de negocio.
- Testeado para business result, payment result & one tap.
=> Remove payment method description on congrats.

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+Plugins.swift
Se corrige el bug que hacia que no se muestre la image de los plugines de payment method en revisa y confirma y en congrats.
=> Set external Payment Method Image

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/String+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXIdentificationType.swift, MercadoPagoSDK/MercadoPagoSDK/UI/BankDeals/PXBankDealComponentRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/BankDeals/PXBankDealDetailsViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXUIImageView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardFormViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/IdentificationViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/SecurityCode/SecurityCodeViewController.swift
- Alta de tarjeta: botones de continuar y anterior están rotos, es difícil presionarlos.
- Alta de tarjeta: Fecha de expiración -> al ingresar caracteres no numéricos, agrega "/" consecutivas.
- Ingreso de DNI: si se ingresa caracteres no numéricos, el label "nombre" blinkea.
- Pantalla de congrats: el signo $ queda desalineado (también se da en iPhone) 
- Pantalla de promociones bancarias, las imágenes están rotas.
- Detalle de promoción bancaria, textfield editable.
- Crash al hacer undo (shake o botón)
=> Fixes iPad

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapService.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentsSelectorView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/FSPager/FSPagerView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift
- Se agrega la animacion del slide en el selector de cuotasç
- Se cambia el tamaño del UIPageControl del seleccionador de tarjetas
- Se agrega la linea separadora en el top del selector de cuotas
=> One tap - Slide Animation

MercadoPagoSDK/MercadoPagoSDK/Services/Alamofire/Alamofire+PXServiceLayer.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Alamofire/Alamofire.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/MercadoPagoService.swift
@edentorres 
Se me ocurrió este pequeño cambio, para hacer escalar el problema que teníamos de  MercadoPadoSDK vs MercadopagoSDKV4 y la función Request.
Lo probe bastante y no vi problemas. Las request se efectuan correctamente. Y obviamente escala a CI y a cualquier otro problema que se nos presentaba previamente. Fijate como lo ves.
De todas maneras, la idea no es meterlo en la RC de OneTap. Lo discutimos entre todos el lunes/martes.
Por ahora lo dejo como "do not merge". Por ahi esto abre la puerta a otra idea que se te ocurre, y termina siendo una solución mucho mejor. Evalualo si queres y decime. 
@demtej Revisalo vos tb.
=> Add ServiceLayer for Alamofire request

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow+PaymentFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDKV4.podspec
- Se soluciona un bug al guardar el esc después de tokenizar en one tap. Se estaba guardando antes de checkear si hay que animar el botón o ir a la pantalla de cvv y eso fallaba
=> [Fix] Save esc after tokenization in one tap

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Plist/mpsdk_settings.plist, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCustomOptionSearchItem+PaymentMethodOption.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCustomOptionSearchItem.swift, MercadoPagoSDKV4.podspec
Hot fix para que deje de crashear la autoseleccion de un solo medio de pago
- PXCustomOptionSearchItem implementa el protocolo PaymentMethodOption 
- Cambio 2
=> Custom payment method option hot fix

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift
- El flujo de inicio de AddCard está mostrando una transición rara cuando arranca. Se está sacando la loading screen cuando aún faltan un par de cosas para hacer el push del VC, así que estoy moviendo el dismiss al método que hace el push.
- También agregué el dismiss en el control de errores en los casos correspondientes y controlé sacando el dismiss de getIdentificationTypes no se esté rompiendo otro flujo (getIdentificationTypes siempre llama a openCardForm).
- Los tests están pasando (a excepción de uno que está roto pero no está relacionado y lo están refactorizando).
- Se probó con la librería integrada en meli y wallet, todo ok
=> Feature/fixing add card navigation on start - Follow up de PR 1838

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC.xcodeproj/project.pbxproj, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/PaymentPluginViewController.m, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantLayout.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
- Se agrega la capacidad visual de soportar subtitulo opcional en OneTap. 
- Este cambio es netamente visual. Todavia el subtitulo no se consumirá por lo cual siempre renderizará el "viejo" y actual layout.
- Dada la complejidad (y cantidad de codigo) de los renders via código. Desarrollé para este caso, un objeto Layout. Que es el encargado segun el caso de generar las constraints de cada tipo de layout.
El TODO:  _Q2 2019 - SP Integration - Get title and subtitle from Preference_.
hace referencia a una tarea que no esta relacionada con este PR. Y es una tarea que haremos
en Q2. Que tiene que ver con resolver de que lugar de la preferencia tomaremos el title y subtitle para OneTap. Sin afectar obviamente integraciones actuales.
La idea de este PR es que ya tengamos soportado esto en el …
=> Subtitle UI Support on OneTap - SP Support

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAdditionalInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAdditionalInfoSummary.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference+AdditionalInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
- Consume title, subtitle, icon and purpose (purchase title) from Additional Info cehckout Pref
- Support pref by id (backend) and pref abierta (SP) - String setter
- Suppport instore retrocompatibility. By item
_**Layout subtitle & title con los dos scenarios de posicionamiento:**_ (Se ve entrecortado por los frames del gif)
_**Ejemplo integración correcta**_
=> SP Support - AdditionalInfo by CheckoutPref

MercadoPagoSDK/MercadoPagoSDK/Models/PXDiscount+Business.swift
Nos liberamos de logica de front para el amount percent off y fixed percent.
Lo tomamos desde backend ya formateado y resuelto, listo para mostrar.
Solo tenemos un default (safe check), en el caso que no venga el name. Donde ponemos "Descuento".
__
Esto se tiene que mergear una vez que el backend este live con este cambio.
El PR de backend todavia esta en draft.
Yo aviso cuando estaria listo para mergear este PR.
Backend related: https://github.com/mercadopago/px-ios/pull/1875
__
=> {MPuntos wallet support} - Get discount name from back

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MoneyIn/MercadoPagoCheckoutViewModel+MoneyIn.swift
Swapping the conditions order avoids a subcase in which the card id was not applied properly. If the user has no customer options but card_id has been set to "debit_card", the debit card option should be autoselected.
=> card id fix

MercadoPagoSDK/MercadoPagoSDK/Core/Managers/ResourceManager.swift
Waiting for payment debe ser **siempre** VERDE.
En Android esto funciona correctamente. Lo alineamos. Ya que hubo issues relacionados que levantaron los integradores.
=> Align with Android, waiting for payment will be green

MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference.swift
Objective: the checkout preference object should start registering the new "processing modes" and "branch id" fields added to the preference service response
=> 2- Checkout preference with processing mode

MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXSummaryAmountBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentService.swift
In the previous implementation a hardcoded field called "processing_mode" of String type was sent in many calls with the value "aggregator" as a query params. This query param is no longer needed and may become confusing as the new "processing_modes" of Array type will be needed for the new implementation to work, therefore it needs to be removed.
=> 4- remove hardcoded processing mode

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPaymentMethodSearchBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
Processing mode and branch id fields obtained in the preference service will be sent back as part of the body in the payment methods call.
=> 5- Redirect preference fields to payment methods service

MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXSummaryAmountBody.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentService.swift
Processing mode and branch id fields obtained in the preference service will be sent back as part of the body in the 'get summary amount' call.
=> 6- new gateway mode fields added to summary service

MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentService.swift
get issuer service will only send a processing mode as a query params if there was only one option and thus could be autoselected, in any other case this query param goes as nil. 
all normal implementations will default to "[aggregator]" and keep sending aggregator as query param, the new case in which only 'gateway' is available will autoselect this mode. If both options are available, nothing will be sent as query param and the logic to determine which issuers should be returned will remain on the backend side.
This is a temporary solution.
=> 7- Get issuer service adapted to new processing mode logic

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckout+ConfigurationServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutServices.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoServicesAdapter.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/InitFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
-Issuers and summary services should use the "processing modes" that are bound to the payment method that has been selected at that time.
-Payment methods service should use the "processing modes" that are allowed by the preference set at initialization
This PR ensures that the right source of "proccesing modes" is used on every each of the aforementioned situations
=> 9- correct proccesing mode use for each service

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Models/MPPayment.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
- Se envían la publicKey y accessToken como query params en el endpoint de /payments para que la procesadora de PX soporte accessToken
=> Procesadora de PX soporta accessToken

MercadoPagoSDK/MercadoPagoSDK/Add_card/AddCardFlow.swift
- Se hace un unsuscribe a la notificación attempToClose.
Esto fixea el caso en en el cual, si un usuario entra y sale varias veces del flujo de alta de tarjeta, al tocar back, hace varios popVC seguidos
=> Unsuscribe to attempToClose Notification when leave AddCardFlow

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantLayout.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderMerchantView.swift
- Se reparan las constraints del title label de One Tap
=> FIX - One tap title label fix

MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderRenderer.swift
- Se hace un hot fix que arregla la alineación del texto del header en las congrats que no son verdes.
=> HOT FIX - Header text alignment fix

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift
Llamamos al módulo de validacion de Biometric **SOLO** cuando tenemos el ESC guardado para esa tarjeta o el pago es AccountMoney o Digital Currency.
Esta lógica o una lógica simil (despues vemos de que manera) la llevamos al módulo de PX AddOn junto con @ericertlMELI 
**NO MERGEAR** todavia, ya que arquitectura va a sacar una build integrada para probar. cc / @fventre
=> Call to biometric only with saved esc

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift
- Se hace un reload de la tableView para que se vean las cuotas en dispositivos que antes no lo hacían con iOS 13
=> Se hace un reload de la tableView para que se vean las cuotas

MercadoPagoSDK/MercadoPagoSDK/UI/WebViewController.swift
- Apple has stated that it will in the near future stop accepting apps that use UIWebView. Migration to WKWebView is to allow apps to submit past that unknown deadline.
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
=> Replace UIWebView with WKWebView

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
- Se arregla un bug por el cual no se enviaban los payment IDs en la mayoria de los casos al hacer el request a endpoint de congrats.
=> HOT FIX - Payment IDs in Congrats request

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapNewCardDto.swift
El backend va a empezar a enviar el valor version dentro de la card de one tap.
Si version == v1, entonces hay que mostrar el viejo alta.
Cualquier caso contrario, de vacio o valor diferente al v1, hay que mostrar el nuevo.
=> Add version check

MercadoPagoSDK/MercadoPagoSDK/Core/Extensions/UIColor+Additions.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Utils.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXText.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Base/PXComponentContainerViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Card/CardsAdminViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsInfoRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsInteractionRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsInteractionsRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsReferenceRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsReferencesRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsSecondaryInfoRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsSubtitleRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Instructions/PXInstructionsTertiaryInfoRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXError/PXErrorRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterRenderer.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXHeader/PXHeaderViewModelHelper.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResourceProvider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
- Se agrega soporte para colores en formato hexadecimal de 8 dígitos (AARRGGBB)
- Se dejan de usar el pxWhite y el pxBlack
- Se agrega la opción de poder agregar colores default a los PXText
=> Fix - Hex colors with alpha

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel+NextStep.swift
Pago de Servicios: Usuario no ve CHO one tap en iOS cuando tiene solo un medio de pago (MLB)
Issue: Al tener un solo medio de pago, se autoseleccionaba el primer medio de pago y paymentData.isComplete() devolvia true enviandonos al checkout viejo.
=> Fix bug1100

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
Se agrega vertical margins para las views que se ubican debajo de MLBusinessActionCardView y que no tenían aplicado un vertical margin.
=> Fix MLBusinessActionCardView  bottom margins

CHANGELOG.md, MercadoPagoSDKV4.podspec
- Se redujo el tamaño de las imagenes
Antes:
Despues:
=> Release 4.34.5

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckoutViewModel+InitFlow.swift
- Se fixea este bug https://mercadolibre.atlassian.net/secure/RapidBoard.jspa?rapidView=2743&projectKey=PXN&modal=detail&selectedIssue=PXN-1153
Al recuperar la preferencia, no se seteaba el payer correspondiente en paymentData, haciendo que flujos que requerian obtener datos del payer fallen
=> Fix medios off

MercadoPagoSDK/MercadoPagoSDK/Core/MercadoPagoCheckout+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXPulseView.swift, MercadoPagoSDK/MercadoPagoSDK/Models/BusinessResult/PXBusinessResultViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCardSlider/PXCardSlider.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXResultViewModel.swift
- Se producia un crash al intentar seleccionar una tarjeta con un indice invalido.
- Se valida que el indice sea valido antes de seleccionar la tarjeta y se agrego un default y un friction para casos no contemplados
=> Fix crash trying to select a card in OneTap

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/MercadoPagoCheckout.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Localize/Localizator.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Localize/PXCustomTranslationKey.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/InitFlow/MercadopagoCheckoutViewModel+InitFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAdditionalInfo.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAdditionalInfoConfiguration.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXAdditionalInfoCustomTexts.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXCheckoutPreference+AdditionalInfo.swift
- Se agrega **px_configuration** y **px_custom_texts** en el additional_info de la pref
```
{
"px_summary": {},
"px_configuration": {
"flow_id": "/multiplayer"
},
"px_custom_texts": {
"pay_button": "Enviar",
"pay_button_progress": "Enviando...",
"total_description": "Total a enviar"
}
}
```
=> Add new values to additional info model

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/Base.lproj/Main.storyboard, ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleSwift/ExampleSwift/Controllers/ViewController.swift, ExampleSwift/ExampleSwift/Storyboards/Base.lproj/Main.storyboard, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
- Se crea la clase `PXPaymentCongrats` que servirá como punto de entrada para los integradores que deseen instanciar *Congrats* sin tener que pasar por el flujo de checkout.
- Se comienza a dar forma a la estructura de `PXPaymentCongrats`, se crean varios setters `public` y otros `internal` para el uso exclusivo del checkout. Hay muchas definiciones pendientes y comentarios que tienen que ver con terminar de entender para que se usa cada campo.
- `PXPaymentCongratsViewModel` conforma con el protocolo `PXNewResultViewModelInterface` para poder ser utilizado como fuente de datos del `PXNewResultViewController`. Su init recibe `PXPaymentCongrats` que es el DTO que finalmente posee todos los campos.
- En la testApp de Swift y Objc se agregan botones que permiten lanzar esta nueva Congrats …
=> PaymentCongrats: Initial structure

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
- La pantalla de recuperos tiene scroll cuando no debería.
- Se subio la view de remedies en `getContentViews()` y se hace un return si existe remedies para que no se incluyan mas vistas
=> Fix PXN-1183

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel+Tracking.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPayerCost+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData+Tracking.swift
En los tracks de /confirm y /result para el medio de pago "credits" no se está mandando información sobre la cuota seleccionada (al igual de como se hace para TC). Se replica el modelo de TC para CC.
=> Add extraInfo for consumer credits

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift
Aunque el pago con credits se le aplicaba el descuento, este no se mostraba en el summary de onetap.
Se agrega el cardId para credits para que se visualice la row de descuentos.
=> Show discounts row in oneTap summary

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapInstallmentInfoView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPayerCost+Business.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Models/PXPayerCost.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXCFTComponentView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Payer/PayerCostCFTTableViewCell.swift
- Se saca la lógica para formatear el texto de CFT y se setea directamente como viene de backend.
=> Feature CFT text

MercadoPagoSDK/MercadoPagoSDK/Core/Managers/ThemeManager.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/OneTapSummaryRow/PXOneTapSummaryRowView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeaderViewModel.swift
- Fix brief color in discounts row for all iOS versions.
- Set horizontal layout for medium size devices when discounts row is displayed.
=> Discounts row improvements

ExampleObjectiveC/MercadoPagoSDKExamplesObjectiveC/MainExamplesViewController.m, ExampleSwift/ExampleSwift/Controllers/CongratsSelectorViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/Extensions/MercadoPagoCheckoutScreens.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentCongrats.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/PXPaymentCongratsViewModel.swift
Se elimina el set del callback al momento de instanciar el NewResultViewController, ahora el callback se setea directamente en el viewmodel para una posterior transformacion en payment Congrats.
=> [Congrats] Remove callback from NewResultViewController init

MercadoPagoSDK/MercadoPagoSDK/Core/Checkout/ViewModel/MercadoPagoCheckoutViewModel.swift
- En ObjC permite enviar nil en el param `preferenceId` del `MercadoPagoCheckoutBuilder`, ocasionando un crash al querer setear el payer (flujo pref abierta) que es nil.
Si vuelven a enviar nil en preferenceId, ahora no se produce un crash y se finaliza el flujo por `PXLazyInitProtocol -> failureWithCheckout` o muestra pantalla de error si no se inicia como lazy
=> Fix nil preference

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultUtil.swift
Se añade el whiteSpace faltante en el label de descuentos, entre el rawAmount y el porcentaje de descuentos  de la Congrats
=> [Congrats] Add whitespace in discount label

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
- [Se alinea con lo desarrollado en Android](https://github.com/mercadopago/px-android/pull/2393)
- Se utilizará en los distintos componentes de Loyalty de la aplicación para mantenerlos siempre actualizados con la información de los puntos y nivel de user.
- Soluciona algunos casos de inconsistencia donde al user en la congrats se le muestra su nuevo nivel (o X cantidad de puntos) y en otros componentes que no se actualizaron con esta información se muestra información del nivel antiguo.
- Se agrega el broadcaster que envía la nueva información de Loyalty a los diferentes integradores mediante el bus de LoyaltyRing
- Simplemente hacer cualquier pago que llegue a una congrats de Mercado Pago, por ejemplo "Pago con QR" que muestra los puntos obtenidos por Loyalty
- Es limpio para todos los …
=> Se utiliza el Broadcaster de Loyalty

MercadoPagoSDK/MercadoPagoSDK/Core/PXCheckoutStore.swift
This PR adds a method to return `validationProgramId` value on PXCheckoutStore
=> Adds a method to return validationProgramId value

ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/Models/OneTap/PXOneTapApplication.swift
Now backend sends behaviours inside applications node so we use it from there, using the old behaviours node as fallback
=> feat: Using behaviours from applications node if they're available

ExampleSwift/ExampleSwift.xcodeproj/project.pbxproj, ExampleSwift/Podfile, MercadoPagoSDK/MercadoPagoSDK/UI/PXFooter/PXFooterViewModelHelper.swift
Before adds a secondaryButton on `PXFooterView` there is a condition to check if the buttons will not be duplicated
Make a payment with wrong `cvv`, on congrats view you should only see one button with text "Pagar con otro medio"
=> BugFix duplicatedButton on congrats

MercadoPagoSDK/MercadoPagoSDK/UI/PXResult/New UI/PXNewResultViewController.swift
Every single time user was on congrats screen, blocked its phone and returned the entire congrats was recreated without removing screens from content view, what was causing this behavior: 
This PR fixes it
Only testable on blue app , because on our test app biometric validation is not required and it that triggers the congrats recreation
=> Removing subviews from content view when screen is recreated

ExampleSwift/ExampleSwift/Helpers/DataExtensions.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Services/PaymentMethodSearchService.swift
Removing support method from `getInit` request on `PaymentMethodSearchService` class
Its not a standard behavior, depending on the response it crashes
Crash link: [here](https://app.bugsnag.com/mercadolibre/mercado-pago-ios/errors/60e8bfd99c7eb40007545edb?event_id=60ee19de007f8dff11c20000&i=jr&m=li)
=> removing print that should only be used for tests porpouse

CHANGELOG.md, MercadoPagoSDKV4.podspec
🚀Private Release - 4.39.5 🚀
- Fix crashes caused because of mapToJSON() method on PaymentMethodSearchService class
- Fix duplicate views on congrats after unlock phone
- Remove forced unwrap from tracks
=> Update change log and bumping app version

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeader/PXOneTapHeaderMerchantView.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapHeader/PXOneTapHeaderView.swift, MercadoPagoSDKV4.podspec
We've added back 'maskToBounds = true' property to header merchant image view for proper image rounding for all source formats
Open a preference with a '.jpg' source header merchant image view
=> fix: Fixed header merchant view cornerRadius

MercadoPagoSDK/MercadoPagoSDK/Flows/PaymentFlow/PXPaymentFlow+Services.swift, MercadoPagoSDK/MercadoPagoSDK/Services/Constants/ApiParam.swift, MercadoPagoSDK/MercadoPagoSDK/Services/MercadoPagoServices.swift
Adds a parameter on congrats request
Make a payment and send a parameter to congrats request
=> Adding payment_type_id on congrats request parameters

CHANGELOG.md, MercadoPagoSDK/MercadoPagoSDK/Core/PXAmountHelper.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXOneTapViewController.swift, MercadoPagoSDK/MercadoPagoSDK/Models/PXPaymentData.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXReview/PXReviewViewModel.swift, MercadoPagoSDKV4.podspec
Now we are using NSDecimalNumber instead of Double for calculations on preferenceAmount, chargesAmount and discountsAmount when needed.
This way we prevent calculation issues that could end on invalid payments by decimal inconsistencies.
If you pay $200 + $8.48 ticket it will return $200.48 with getRawAmount(), before it used to return $200.47999999999
=> Fix: raw amount rounding issue

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/UI/PXCreditsViewModel.swift, MercadoPagoSDK/MercadoPagoSDK/UI/Components/PXTermsAndConditionsTextView.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXCard/DefaultCards/ConsumerCreditsCard.swift, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
- Creation of PXTermsAndConditionsTextView, for reuse in Remedy screen;
- Adjustments by ConsumerCreditsCard to remove the extension equivalent to PXTermsAndConditionsTextView;
- ConsumerCreditsCard adjustments for the credit market logo to be at the top left when necessary;
- Adjustments in PXRemedyView to follow the layout.
=> [FEATURE] - [PXN-2403] - PXRemedyView layout fixes for correct viewing ConsumerCreditsCard

MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlow.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/OneTap/OneTapFlowModel.swift, MercadoPagoSDK/MercadoPagoSDK/Flows/TokenizationFlow/TokenizationService.swift
Added extra step to oneTapFlow for tokenizing without cvv/ESC for mode = .optional
Before, if a card has securityMode == .optional, it didn't request cvv nor ESC but was not tokenizing too, causing the payment flow to fail.
Now, if it's optional, it gets tokenized without CVV nor ESC anyways.
Try changing security mode between .optional / .mandatory with any card
=> feat: Added extra step to oneTapFlow for mode = .optional

CHANGELOG.md, MercadoPagoSDKV4.podspec
🚀Private Release - 4.46.0 date: 16/09/2021 🚀
- Showing modal when remedies card option given from BE is Mercado Creditos (disabled until tracks are done)
- Card size on remedies dynamic according to BE response (disabled until tracks are done)
- Tokenizing without cvv/ESC
- Terms of use removed from customCard and added to top of payButton
=> Updating changelog and podspec

MercadoPagoSDK/MercadoPagoSDK/UI/WebViewController.swift
We do not allow anymore universal links to be open through our `WKWebView`
- You have to have Mercado Livre app on the phone
mock `px_mobile/v2/checkout` request with with this url `https://run.mocky.io/v3/a1ee741a-1e59-42a6-85f7-7ce4ffa38285 ` open terms and conditions on mercado creditos card, after this tap on `Ver termos e condições gerais` and the behavior should be not open Mercado Livre app and show you the terms and conditions on WKWebView
=> Bugfix deeplink through terms and conditions

MercadoPagoSDK/MercadoPagoSDK/UI/SecurityCode/PXSecurityCodeViewController.swift
Make the resetButton method from PXSecurityViewController to run in the main thread, so it doesn't crash the app when making UI updates.
Crash reference:
https://app.bugsnag.com/mercadolibre/mercado-libre-ios/errors/613793b46d62880007112650?pivot_tab=event
=> Fix main queue layout update crash on PXSecurityViewController

.fastlane/Fastfile, CHANGELOG.md, Gemfile, Gemfile.lock, MercadoPagoSDK/MercadoPagoSDK/UI/PXRemedy/PXRemedyView.swift
Fix account money remedie suggested value. There was an old business rule that was removed to fix the issue and make account money behave like any other payment method.
Execute a failed payment with a card that has taxes and get account money as remedie. If the value suggest for the account money is the proper one, then it is good.
=> (Fixed)[PXN-2819] - Fixed bug with wrong suggested value for account money remedie
